### ISSUE TITLE
Test authentication for AzureAD & confirm nothing else needed from the client

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#1]
## Request
Tomorrow I will have full specs for you, but can you please try authenticating with this test instance of Microsoft Azure AD in case I need to ask the client for any more information (they're based in the US, so turnaround might be slow)?

## Creds
See LP for `Microsoft Azure (Women for Women)`... this is my Microsoft account which has been granted access to different WfW environments. The below test one is what we want to connect with: 
- Test instance name is:  `WfWI Test Environment`
- Domain name: `http://w4wtest.onmicrosoft.com/`
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/9ba3d12b-f8c7-4007-9536-01d197171dea)

## API Docs
We use the Microsoft Graph API to connect with Azure AD: https://docs.microsoft.com/en-us/graph/use-the-api
This links to authentication basics: https://docs.microsoft.com/en-us/graph/auth/auth-concepts

You may need to register the app first...? 
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/00633da3-74db-403b-9691-0a94cf1a1001)

**Comment by aleksa-krolls** [comment]
@lakhassane FYI, the full specs for this project are now added to issue #2.

**Comment by lakhassane** [comment]
@aleksa-krolls feedbackcs from testing here. I configured Azure and Postman to test. 
We are able to get `access token` for future requests. However, it seems like the account I am using from Lastpass credentials does not have sufficient privileges for the needed operation. Check output from `GET /users`

```
{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "date": "2020-10-28T16:47:34",
            "request-id": "[REDACTED]"
            "client-request-id": "[REDACTED]"
        }
    }
}
```

**Comment by taylordowns2000** [comment]
@aleksa-krolls , Mamadou has confirmed that he's able to authenticate, generate an API token, and make a successful request to a protected API endpoint on AzureAD. Closing this issue.
