### ISSUE TITLE
Mailgun run fails with `401` error

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#102]
## Describe the bug
See Jira issue: https://openfn.atlassian.net/browse/OFGS-294
Run failure: https://www.openfn.org/projects/p56pxp/runs/061797b8-a8ae-75b0-9bab-022b615af87c

## To Reproduce
1. Here is state: https://www.openfn.org/projects/p56pxp/messages/06179700-54ff-79f0-b667-3c80f0e118f7

2. **To test, run against this test expression** (which is very similar to the job that failed, but email recipients are us): women-for-women/test__sendWelcomeEmailProd.js at master · OpenFn/women-for-women 

### expression.js
All mailgun jobs: https://github.com/OpenFn/women-for-women/tree/master/jobs/production

### state.json
See LP for `WfWI Mailgun Prod`

**Comment by taylordowns2000** [comment]
@aleksa-krolls , it looks like this job doesn’t use the mailgun adaptor. Do you know why?

Other jobs in this project use `language-mailgun`. This one uses `language-http` and is labelled as `[Sendgrid]`—which is another kind of email-as-a-service app.

As a matter of fact, it looks like there’s a near copy of three jobs (2a, 2b, 3) built using both `language-http` _and_ `language-mailgun`. I don’t see any errors on the jobs using `mailgun`, but see the `sendgrid` ones haven't succeeded in quite some time.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Looks like the user manually triggered this job by mistake... my bad, I saw it was an email run and knew that only the Mailgun jobs were on, so assumed that was the issue here. 

@ritazagoni Please look out for a Matias response and close out the Jira issue accordingly.
