### ISSUE TITLE
upsertTransactionDDV2: Job skips upsert, does not insert any Opp records

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#103]
## Describe the bug
The message state is full of Opps to insert, but the run log says `No items in Opportunity array. Skipping bulk upsert operation.`... why does it think there are no opps to insert?
https://www.openfn.org/projects/pdv34m/runs/06188c99-afb7-7276-9baf-bdbb58b72d5c

## To Reproduce
Feel free to re-run on prod: https://www.openfn.org/projects/pdv34m/runs/06188c99-afb7-7276-9baf-bdbb58b72d5c

### expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionDDV2.js

### state.json
See LP for `WfWI Salesforce Production`
https://www.openfn.org/projects/pdv34m/messages/0617e95f-096d-7d03-be9a-5774d2a5bc38

## Expected behavior
We should be inserting 1 Opp for every transaction `json` item

**Comment by lakhassane** [comment]
@alek there is a change in the json we are upserting.

The previous state was having this `"DDId": ""` but currently the new failing one have `"DDid": ""`  (with lowercased 'i').

Do you know why this change and what is the correct key value. That's why the job can't see any Opps to upserting when filter by DDId.

**Comment by lakhassane** [comment]
Update done to check for both format: https://www.openfn.org/projects/pdv34m/runs/06189107-3969-7749-a70b-4fd332061016

**Comment by aleksa-krolls** [comment]
@lakhassane Your fix does not seem to be working, seeing some issues.
See this run: https://www.openfn.org/projects/pdv34m/runs/0618912a-75a2-7776-b7c7-b2c0ead22307
1. It was successful BUT I see lots of `undefined` strings instead of `DDid` (or `DDId`). Search the run log for `undefined` to see what I mean. 
e.g., `'npe03__Recurring_Donation__r.Committed_Giving_ID__c': 'WFWI120720172303530350undefined',`
2. Not all Opps were created. For example, if you look at the message state, there is one item with `"DDid": "778811"`... however I cannot find this item in the run log, so I don't think an Opp was created for this row. 
```
 {
      "Amount": "22",
      "CampaignCode": "Sponsorship",
      "ClientName": "Women for Women",
      "DDRefforBank": "WFWI001206",
      "DDid": "778811",
      "Date": "25/1/2020 00:00:00",
      "PrimKey": "WFWI130720170942150802",
      "PromoCode": "UKSPWEBLP",
      "Status": "Paid",
      "TransType": "Sponsorship",
      "reason": ""
    },
```
Can you please make sure the job is properly evaluating `DDid` OR `DDId`? 
Feel free to re-run this run on prod to make sure `778811` is inserted as an Opp.

**Comment by lakhassane** [comment]
@aleksa-krolls this is on me. I check for DDid only when filtering and removing unwanted object but not when mapping.

See last run here: https://www.openfn.org/projects/pdv34m/runs/0618beb3-dbad-7a0b-97c6-b95605beacca

For `DDid: 778811` look at line `329` of the last run
