### ISSUE TITLE
Job changes for dynamically getting CSV files from sftp

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#104]
## Background, context, and business value
We have an integration configured between SFTP server, OpenFn, and Salesforce that automates the extraction of donation data saved in CSV files on the SFTP server, and then transformation & loading into the target Salesforce CRM & donation management system. 

Currently we have a job that will get specific `.csv` files from an SFTP server every time it runs. However, the current job expects that we know the _exact_ file name, which changes every time a new extract is created because the date is updated. For example, over the last 3 weeks, 3 files of the same type but slightly different names were produced: 
`wfwi custom cc fields 17122021`
`wfwi custom cc fields 10122021`
`wfwi custom cc fields 03122021`

## The specific request, in as few words as possible
Two requests: 
1. Make changes to fetch any files with specified key words, and don't require us to hardcode the full file name in the job. 
For example, I'd like to specify the key words `wfwi custom cc fields` and it will extract all files with those matching keywords (e.g., `wfwi custom cc fields 10122021` AND `wfwi custom cc fields 17122021`) from the SFTP server. 
```
const fileNames = [
`wfwi custom cc fields`, 
...
]
```
This way, if the date in the file name is updated every week... I won't need to update the file names referenced in the job. 
When Messages of extract CSV data are posted to the OpenFn Inbox, they should include: 
```
"fileName": "wfwi Custom CC fields 10122021.csv", //csv file name
"fileType": "wfwi custom cc fields", //key words used to get this file
```

2. Also, currently when we get files from the SFTP server, we post them back to the OpenFn Inbox as Messages. I've noticed that sometimes we don't trim the rows, so an almost empty item in the array is often included. 
For example, see L26 in [this Message](https://openfn.org/projects/wfwi-committed-giving/messages/061c1cfa-78b0-7632-ac4a-4b2bb4444670)
```
{
      "ClientName": ""
 }
```
This^ looks like an empty row in the CSV file and should be trimmed before including in the Message posted back to OpenFn to avoid errors when the triggered job runs. 

## state.json
See LP for `WFWI SFTP`
Feel free to test posting to this OpenFn project's Inbox: https://openfn.org/projects/wfwi-committed-giving/jobs

This job will run on a timer to check the sftp server for new CSV files with matching key words: 
https://openfn.org/projects/wfwi-committed-giving/jobs/jywrpw

## adaptor
sftp

## expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js
https://openfn.org/projects/wfwi-committed-giving/jobs/jywrpw

## output.json
*For each file found*, post Messages posted to the OpenFn Inbox for  
If the key word entered in the job is `wfwi card master`, then I'd expect 2 Messages to be posted to the OpenFn Inbox where `fileType: 'wfwi card master'` and the `fileName` of the 2 files currently on the sftp server will be ` 'wfwi card master 10122021'` and ` 'wfwi card master 17122021'`.

**Comment by elias-ba** [comment]
@aleksa-krolls this is now implemented and pushed. See [this commit](https://github.com/OpenFn/women-for-women/commit/e7145c1e16c5b3579cb23b3e0f7e01e3d4dd5bc5) and [this one](https://github.com/OpenFn/women-for-women/commit/4457c8d79435c8c327787e4d27eaca6e1e8c179f) too. Please review and lmk.
