### ISSUE TITLE
After creating new `Contact` records for Honoree Sponsors, link RDs to these Contacts

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#105]
## Background, context, and business value
WfWI uses Committed Giving to collect donor data, and sometimes a person will make a donation as a gift to a friend/family... so WfWI wants to log this gift recipient as a Contact so they can notify them of the gift made in their name. 
In issue #87 , we implemented a change to create `Contact` records if recipient emails 

## The specific request, in as few words as possible
We now want to add an operation to both the custom jobs, so that if a `Contact` is created in the current last step... then we should now update the `Recurring Donation` to link to this newly created `Contact`. This same change needs to be implemented in both the custom credit and debit jobs...

**upsertCustomCCV2.js** 
If Contact created via [L75-L107](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomCCV2.js#L75-L107)...
1. Upsert `npe03__Recurring_Donation__c` where 
2. extIdField: `'Committed_Giving_ID__c': dataValue('CCID')`
3. map: `Sponsor__c` = Salesforce record `Id` of newly created Contact (returned after Contact successfully inserted in previous operation)

**upsertCustomDDV2.js** 
If Contact created via [L81-L115](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomDDV2.js#L81-L115)...
1. Upsert `npe03__Recurring_Donation__c` where 
2. extIdField: `'Committed_Giving_ID__c': dataValue('DDID')`
3. map: `Sponsor__c` = Salesforce record `Id` of newly created Contact (returned after Contact successfully inserted in previous operation)

## state.json
See LP for `WfWI OpenFn sandbox`
1. CC state.data: https://openfn.org/projects/wfwi-committed-giving/messages/061ca60a-481e-76b8-b1cc-54e4b9e29622
2. DD state.data: https://openfn.org/projects/wfwi-committed-giving/messages/061c10b2-fdf5-777b-9f8c-8c42b898a17d

## adaptor
salesforce

## expression.js
1. CC job: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomCCV2.js
2. DD job: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomDDV2.js

## output.json
After creating Contact records in SF, related Recurring Donations should link to these Contacts with the `Sponsor` field.

**Comment by lakhassane** [comment]
@aleksa-krolls updates done. This is ready for testing

**Comment by aleksa-krolls** [comment]
@lakhassane I'm testing on the latest csv export, and encountering [this run error](https://www.openfn.org/projects/wfwi-committed-giving/runs/061dbcb1-9423-75cb-a6cd-94271d32057b), which means we need to add the mapping `npe03__Contact__c` to our upsert RD operations (see L108 and L120). 

To find the Id for `npe03__Contact__c`, we need to a soql query as follows to get the Id and map on L108 and 120. 
```
SELECT npe03__Contact__c FROM npe03__Recurring_Donation__c WHERE Committed_Giving_Direct_Debit_ID__c = {DDID}
```
Can you please implement this change and run this Message to test? 
https://www.openfn.org/projects/wfwi-committed-giving/messages/061dbc8c-3140-7729-b47b-9cbe4be12fee
