### ISSUE TITLE
Duplicate email check removes csv rows where email is blank

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#107]
## Background
Per issue #55, we remove rows with duplicate emails after fetching CSVs from the sftp server. 
https://github.com/OpenFn/women-for-women/blob/11e262a327b436ef345f6b2b21e709286fcf4e0e/jobs/committed/1.fetchJSON_Donors.js#L45-L60

However, I think this logic is removing rows where email is blank/not defined. If that's the case, then we should ensure these rows are not considered "duplicates" and that these donors are included in the Messages posted back to the OpenFn Inbox. 

For example, if you run [this job](https://www.openfn.org/projects/wfwi-committed-giving/jobs/jywada) then 2 Messages should be created where one of these will contain the row data for donor with `"PrimKey": "250520171100020712WomenforWomen"`. 
(Currently I'm finding on platform that this donor has been filtered out.)

## Request
If a donor row does not have an `EmailAddress` defined (e.g., donor with `"PrimKey": "250520171100020712WomenforWomen"`), do not check for duplicates for this row and ensure this row is included  in the Messages posted back to the OpenFn Inbox. 

## adaptor
sftp

## state
See LP for `WFWI SFTP`
Feel free to run job E0 on prod to test: https://www.openfn.org/projects/wfwi-committed-giving/jobs/jywada

## expression
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js

## Testing notes
Search the 2 Messages created via this job for the string `250520171100020712WomenforWomen` to confirm this donor has been included in these messages.

**Comment by lakhassane** [comment]
@aleksa-krolls issue solved. The missing row is included here: https://www.openfn.org/projects/wfwi-committed-giving/messages/061dc4db-cc60-79be-9de3-eaed54005da2

**Comment by aleksa-krolls** [comment]
@lakhassane is this resolved now? It look like it per the new messages you created with this donor example?

**Comment by lakhassane** [comment]
@aleksa-krolls issue solved here: https://www.openfn.org/projects/wfwi-committed-giving/runs/061dd911-679e-7ea1-b601-0dfa2ff8629d

**Comment by aleksa-krolls** [comment]
@lakhassane can you pls confirm what salesforce adaptor version all my jobs for this project should be on now?
