### ISSUE TITLE
Email error notification when Donor sftp extract job fails with error

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#108]
## Background
This job [1.fetchJSON_Donors.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js) runs on a timer basis to fetch a csv file from an `sftp` server to extract a list of donors to later upload to a Salesforce CRM used by the NGO. 

Because Salesforce doesn't allow for duplicate Contacts with the same email address, this job currently throws an error if it detects duplicate email addresses in the csv file it extracts from the SFTP server. See example run and `Error: Potential duplicate rows` message: https://www.openfn.org/projects/wfwi-committed-giving/runs/061f776a-a9bf-7a1c-b859-f7383d7c88e1

## Request
When this job to extract donor fails because of duplicates, we should now email the Women for Women administrators. 

I've already drafted the job to send a custom email alert via Mailgun. Please help me to dynamically replace the variable `errorMessageFromParentJob` (see below) in the email HTML body with the Error Message from this job run: https://www.openfn.org/projects/wfwi-committed-giving/runs/061f776a-a9bf-7a1c-b859-f7383d7c88e1
https://github.com/OpenFn/women-for-women/blob/4960a0aeda118925dc0a79e4319b7e6f1629bd14/jobs/committed/emailErrorAlert.js#L9-L14

This email body should therefore output as follows: 
```
Dear admins, 

Duplicate donors were detected in the latest Committed Giving export. Please review the duplicates in Committed Giving to merge the records. 

Error: Potential duplicate rows detected in Committed Giving. See rows: [
  "emma.bennett27@btinternet.com",
  "susieking@yahoo.com"
]

Contact OpenFn at support@openfn.org with any questions.
```

## adaptor
Mailgun

## expression
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/emailErrorAlert.js
On OpenFn: https://www.openfn.org/projects/wfwi-committed-giving/jobs/jywada

## state
See LP `WfWI Mailgun Prod`
https://www.openfn.org/projects/wfwi-committed-giving/runs/061f776a-a9bf-7a1c-b859-f7383d7c88e1

**Comment by lakhassane** [comment]
@aleksa-krolls we made the change in the `emailErrorAlert` job. See example run here (I changed to receive the email myself): https://www.openfn.org/projects/wfwi-committed-giving/runs/06216601-9413-7f73-bb7c-a4a17b9f8a07

**Comment by aleksa-krolls** [comment]
@grayey There was a failed donor run that triggered this email - see here: https://www.openfn.org/projects/wfwi-committed-giving/runs/06221c59-bb30-746c-97ac-7cc4dd48d3a6

Only L14 of this run failure log was included in the email alert triggered (see screenshot). 
<img width="845" alt="Screen Shot 2022-03-04 at 7 55 41 AM" src="https://user-images.githubusercontent.com/16758106/156723323-fce2eac3-ecc5-41a2-96b8-a139b2319978.png">

However, `errorLine` in the [emailErrorAlert.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/emailErrorAlert.js#L25) should include ALL log lines after L14... so L14-31 from [this failure](https://www.openfn.org/projects/wfwi-committed-giving/runs/06221c59-bb30-746c-97ac-7cc4dd48d3a6) should have been included so that the email recipients could see a list of all the emails that were flagged as duplicates. 
https://github.com/OpenFn/women-for-women/blob/24e9b562cf8bcadfeacca3af4ccef67e65a1a278/jobs/committed/emailErrorAlert.js#L25

## To replicate/test
1. Locally, update [emailErrorAlert.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/emailErrorAlert.js#L25) to only send an email to YOUR email (you can comment out the `to` and `cc` mappings... and set one `to` mapping to go to your email address.
2. To generate state for the email job, you can re-run this parent job that triggers the email one: https://www.openfn.org/projects/wfwi-committed-giving/runs/06221c59-bb30-746c-97ac-7cc4dd48d3a6
(You can re-run this on platform OR locally using the credential `WFWI SFTP`)

Once you have it working locally, please push to a branch and let me know when ready for review... thanks!

**Comment by grayey** [comment]
@taylordowns2000 this will be picked up later today.  For now, I've looked throug the requirements and installed the mailgun adaptor

**Comment by aleksa-krolls** [comment]
PR in review: https://github.com/OpenFn/women-for-women/pull/110
@taylordowns2000 pls lmk whenever review and merged; not urgent.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , PR approved, waiting to merge because I can't actually see emails in mailgun.
