### ISSUE TITLE
ReferenceError [Error]: Cannot access 'fields' before initialization

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#11]
## Describe the bug
All runs are failing with the error `ReferenceError [Error]: Cannot access 'fields' before initialization`. See example: https://www.openfn.org/projects/2976/runs/10475609

Q: Is this error related to the latest change request with the console.logs? Or something else? (I want to understand where we missed testing)

### expression.js
`upsertUser.js`

### state.json
See LP for `Microsoft (Women for Women)`. 

Here is a Message to use for state: https://www.openfn.org/projects/2976/messages/10097747

## output
Please ensure these runs succeed on prod: 
https://www.openfn.org/projects/2976/runs/10491871
https://www.openfn.org/projects/2976/runs/10491827
https://www.openfn.org/projects/2976/runs/10491716

**Comment by aleksa-krolls** [comment]
@lakhassane Can you look at this first today? The client has a demo at 9am ET.

**Comment by lakhassane** [comment]
@aleksa-krolls it's done here

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks, but some related issues still popping up: 
https://www.openfn.org/projects/2976/runs/10498643
https://www.openfn.org/projects/2976/runs/10498649

Also, can you please answer my `Q` posed in the request... merci :)

**Comment by lakhassane** [comment]
RE your question: Yes this is because of the console.logs. I added one console.logs #L647 before destructuring the value used inside (fields) thus the error. This error would pop up each time you were creating a new user

@aleksa-krolls  these 2 errors are due to the fact that Work Email is null on state. Is this a normal behavior ? If yes, I will add a condition to test if empty. But beware of the fact that if it is null user principal name will also be null and I don't know if that is wanted.

**Comment by aleksa-krolls** [comment]
@lakhassane I will discuss with the client, but I think we need to handle for scenarios where the Bamboo user forgets to specify `Work Email`. So in this case...

Like with all employee updates, first check...
1. If "Status": "Active" &&
2. If "Employment Status" = any of [these values]:(https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1247678326)

If these both are true AND `Work Email` is null, please force a failure and log the error `No Azure actions taken because 'Work Email' not provided.` ... No point in making Azure updates if we don't have this email input. 

@jedbgold Please note this new error message for the documentation. _Later this afternoon_ (after we know Matias's demo is over), please run through all testing scenarios to make sure everything is working as expected.

**Comment by aleksa-krolls** [comment]
@lakhassane Working great now and demo-ready, thank you!
