### ISSUE TITLE
Send Welcome Email Job Change Request

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#12]
## The specific request, in as few words as possible

This refers to current job in OpenFn called `Send Welcome Email`

Everything remains the same except now when the 'New Employee' email flow is triggered:
1) Send the current welcome email to `Work Email` with respective `HR Divisional Officer Email` cced. 
2) Send the current welcome email with password information removed to `Supervisor Email`.

See mappings here: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1626891982 

Note that new logic needs to be applied for point 1 above.

The new logic requirements are:
1) Look up 'HR Divisional Officer Email' by referencing the 'Division' field of the employee in the BambooHR webhook. In the W4W Integration Mappings workbook, there is a sheet called 'HR Division Email Addresses'. Use the table in `HR Division Email Addresses` for referencing purposes. Please see this link for the sheet: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=925593089

**Comment by jedbgold** [comment]
@aleksa-krolls hold off on this issue. Let's wait until we get 100% confirmation from Matias. I sent him an email today and waiting to hear back

**Comment by aleksa-krolls** [comment]
@jedbgold Did you get what you need from Matias? I'd like to get this into the backlog sometime today, so please let me know whenever ready for review and if a quick chat is needed to clarify the requirements.

**Comment by jedbgold** [comment]
Nope. When I sent the email to Matias on Wednesday morning (nov 25) I got an out of office saying that he will return on Monday Nov 30th.
