### ISSUE TITLE
Get CSVs job fails because of TypeError

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#120]
## Describe the bug
In the middle of fetching CSV files from the SFTP server, the job throws this error: 
```
Connected. ✓
Parsing rows to JSON.
Stream finished.
3
TypeError [Error]: state.data[0].split is not a function
```

## To Reproduce
1. Re-run this failed run: https://www.openfn.org/projects/wfwi-committed-giving/runs/0647fd69-1f3e-7ca0-b277-60da794bb7f1

### expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js

### state.json
- configuration: see LP `WFWI SFTP`
- data: {}

## Expected behavior
Nightly the job runs to get CSV files and post in chunked messages to Inbox. 

## To test/resolve
Feel free to re-run the job locally to inspect the problem. 
## Toggl
`WFWI Support 2023`

**Comment by aleksa-krolls** [comment]
hey @mtuchi please prioritize this when you're online, and lmk if questions - thanks!

**Comment by mtuchi** [comment]
@aleksa-krolls noted 👍🏽 , what toggl project should i use ?

**Comment by mtuchi** [comment]
> @mtuchi what's the status here?

@aleksa-krolls there is an issue with the latest adaptor that the job was using, we are trying to sort this out with new improvements coming to the sftp adaptor See this PR https://github.com/OpenFn/adaptors/issues/252#issuecomment-1580997656

Mean while i have changed the adaptor version to the older version and the job is now working as expected - https://www.openfn.org/projects/wfwi-committed-giving/runs/06480a6b-836a-7a56-ad09-92ece954752d

I think it's important to optimize this job and other jobs that use the `sftp` adaptor once we have the latest release of `sftp` adaptor. I am making the necessary improvements in this PR https://github.com/OpenFn/women-for-women/pull/121

**Comment by aleksa-krolls** [comment]
Thanks for the update @mtuchi. Because it's working now, I'm going to close this issue, but please reach out to chat about the new `sftp` adaptor version when it's ready so we can consider the impact on existing jobs and whether we should make updates.
