### ISSUE TITLE
sftp bug with CSV parsing when commas in cell values

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#123]
## Describe the bug
When our job extracts the CSV file `wfwi Donors 20230831.csv` from an sftp server, the values for `Status` and `date` are being mixed up. 

❌ What I'm seeing in the OpenFn JSON messages generated: 
```
"PrimKey": "WFWI311220182116010002",
"Gift Aid Status": "02/03/2023 13:21:4",  //date value mapped to status field
"Gift Aid date": "True",
```
✅ What I expect to see: 
```
"PrimKey": "WFWI311220182116010002",
"Gift Aid date": "02/03/2023 13:21:4",  //date value correctly mapped to date field
"Gift Aid Status": "True",
```
When I look at the CSV file, it looks good... so this looks like an issue when we convert the CSV to JSON. See feedback from the client that is creating these CSVs: 
```
I checked the mentioned CSV file and the record primkey WFWI220220192144130645. 
All looks fine in the CSV file. My guess it that you’re not using text qualifier your end, 
and the reason for these values not populating correctly for this specific record, is 
the comma in the Address1 field. In consequence the comma splits the text and 
shifts everything to the right by one column. That’s why Gift Aid Status column populates 
with LastChangedDateTime value, ‘Gift Aid Date’ with ‘Gift Aid Status’ value and the ‘Gift 
Aid Date’ value ends up in ‘CampaignCode’ field, and so on.
```

## To Reproduce
1. Run this job locally: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_onDemand.js
2. Search the JSON output for `"PrimKey": "WFWI311220182116010002"` and compare `Gift Aid date` and `Gift Aid Status`

### expression.js
Any changes you make to fix this job will need to be applied across all get CSV jobs: 
1. [1.fetchJSON_onDemand.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_onDemand.js)
2. [1.fetchJSON_Donors.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js)
3. [1.fetchJSON.js](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js)

#### adaptor
`language-sftp@0.8.5`

### state.json
FYI this job is currently pointing to [this project's inbox](https://www.openfn.org/projects/wfwi-committed-giving/messages). 

```json
{
  "configuration": ["SEE LAST PASS: 'WFWI SFTP'"],
  "data": {},
  "cursor": n/a
}
```

## Expected behavior
I expect the correct values to be matched to the correct keys so that the JSON output matches the CSV: 

✅ Output I expect to see: 
```
"PrimKey": "WFWI311220182116010002",
"Gift Aid date": "02/03/2023 13:21:4",  //date value correctly mapped to date field
"Gift Aid Status": "True",
```

## To test/resolve
1. After the desired output is working locally, please push all changes to a branch and let me know when I can test.

**Comment by mtuchi** [comment]
@aleksa-krolls i have added the fix on #124

important things to note 
1.  The correct date for `"Gift Aid date": "31/12/2018 21:16:00"` not the date mentioned in this issue,
2. Update sure to update the sftp adaptor version to `v0.8.6` on openfn.org
