### ISSUE TITLE
Updates to `upsertDirectDebits` and `upsertTransactionDDV2` jobs 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/women-for-women#125]
## Background, context, and business value

Make several updates to how we upsert  Recurring Donations and Opportunity objects in Salesforce, based on the CSV data received from Committed Giving. [See README](https://github.com/OpenFn/women-for-women/tree/master#committed-giving--salesforce-integration) for original solution overview. 

## The specific request, in as few words as possible

Makes several updates to the workflow steps & field mappings of the `upsertDirectDebits` and the `upsertTransactionDDV2` jobs. **See the [V2 Lucid diagrams](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?page=N8DqYFSePrd6&invitationId=inv_2ffe14b1-2f75-492b-b67c-5862570d67a4#)** if you want to leave any comments. 

### (1) `upsertDirectDebits` job updates:

Before upserting `npe03__Recurring_Donation__c` apply the transformations below. These mappings are highlighted purple in the [mapping specifications](https://docs.google.com/spreadsheets/d/1_vg4OUB2S0wFLj7a_7xlbxTweAQSL4WjPJLdvvazkow/edit#gid=1424769387) in the "Direct Debits" tab. 

1. Apply the following logic to set the mapping for the RD `Closeout_Date__c` field.  
-- If `CancelDate` (from the message) == "", return `undefined` for `RD.Closeout_Date__c`
-- If `CancelDate` != ""  and `PaymentFrequency` (from the message) == "Monthly", set `RD.Closeout_Date__c  == CancelDate`
-- If `CancelDate` != ""  and `PaymentFrequency`  == "Annually", set `Closeout_Date__c === LastClaimDate + 364 days` (format YYYY-MM-DD)

2. Always return `"Closed"` for the `npe03__Open_Ended_Status__c` field.  

After upserting `npe03__Recurring_Donation__c` for a given row, also upsert related `Opportunity` records for each row. The UUID for upsert is `CG_Pledged_Donation_ID__c`. These mappings are highlighted green in the [mapping specifications](https://docs.google.com/spreadsheets/d/1_vg4OUB2S0wFLj7a_7xlbxTweAQSL4WjPJLdvvazkow/edit#gid=1424769387) in the "Direct Debits" tab. 
- For active donations, if `CancelDate == ""`,  set `Opp.StageName == "Pledged"`, `Opp.Amount== Amount`, and `Opp.CloseDate == Date`. 
-  For closed donations, if `CancelDate != ""`, set `StageName` == "Closed Lost"

**Find the remaining mappings in the mapping [spec](https://docs.google.com/spreadsheets/d/1_vg4OUB2S0wFLj7a_7xlbxTweAQSL4WjPJLdvvazkow/edit#gid=1424769387).** 

<img width="776" alt="image" src="https://github.com/OpenFn/women-for-women/assets/80456839/d7828d5e-fed0-4c29-ae2d-1710347f1f8f">

### (2) `upsertTransactionDDV2` job updates:

The new UUID for upsert is `CG_Pledged_Donation_ID__c`.  The mappings below are highlighted green in the [mapping specifications](https://docs.google.com/spreadsheets/d/1_vg4OUB2S0wFLj7a_7xlbxTweAQSL4WjPJLdvvazkow/edit#gid=617692149) in the "Transactions DD V2" tab. 

**Refer to the workflow diagram to see when the 2 different Opportunity steps are executed:** 

(1) When donation _is NOT cancelled_, upsert "pledged" Opportunities to schedule the next donation:
- Set `CG_Pledged_Donation_ID__c` equal to `DDid` + `NextDate` (format: YYYY-MM-DD) +  "Pledged" separated by underscore  (e.g., `79111000_2023-10-01_Pledged`)
- Set `StageName` equal to `"Pledged"`

(2) When donation _is cancelled_, upsert existing "pledged" Opportunities to close out future opps:
- Set `StageName` equal to `"Closed Lost"`
- If `PaymentFrequency == "Monthly"`,  set `CG_Pledged_Donation_ID__c` equal to `DDid` + `LastClaimDate + 1 Month` (format: YYYY-MM-DD)  +  `"Pledged"` (e.g., `1179811_2023-09-25_Pledged`)
- If `PaymentFrequency == "Annually"`,  set `CG_Pledged_Donation_ID__c` equal to `DDid` + `(LastClaimDate + 1 year)` (format: YYYY-MM-DD)  +  `"Pledged"` (e.g., `1179811_2024-09-25_Pledged`)

![image](https://github.com/OpenFn/women-for-women/assets/80456839/fe33e3a4-c9cf-4754-a80d-75a3a5188df2)

## state.json
Job 1 data - Direct Debits sample message: https://github.com/OpenFn/women-for-women/blob/master/sampleData/CG_directDebits.json

Job 2 data - Transactions DD sample message: https://github.com/OpenFn/women-for-women/blob/master/sampleData/CG_transactionsDD.json

```json
{
  "configuration": ["See WFW Full Sandbox Sept 2023"],
  "data": { "See message links above" },
  "cursor": "NA"
}
```

## adaptor
Salesforce 
- existing jobs are running on `v2.7.3` --> but we should probably get them on the latest version

## expression.js
Create a new branch off of `master` and push to a new `staging` branch for testing
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDirectDebits.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionDDV2.js

## output.json
1. `upsertDirectDebits` job should upsert `Reucurring Donations` and `Opportunities` records
2. `upsertTransactionDDV2` job should upsert `Opportunities`

See [test suite](https://docs.google.com/spreadsheets/d/1ixrIlaufUcQG_gBFYX1GugAnz0eDO2Kd2tjkubZm5x4/edit#gid=1263965928).

**Comment by aleksa-krolls** [comment]
@mtuchi this is ready to be worked on, but adding to the bottom of the backlog. Sync with Aicha this week, whenever you're ready to get started. 

@daissatou2 can you set up a new "staging" project on OpenFn.org? We don't have one for this project, but would be good to manage the test data and tests separately.

**Comment by daissatou2** [comment]
@mtuchi I see that you've already started on this. FYI the mappings for the following fields have changed. Check out the [mapping specifications](https://docs.google.com/spreadsheets/d/1_vg4OUB2S0wFLj7a_7xlbxTweAQSL4WjPJLdvvazkow/edit#gid=1424769387) for the latest. 

**Direct debits:**
`Active__c`
`Closeout_Date__c`
`CG_Pledged_Donation_ID__c`

**Transactions:** 
`CG_Pledged_Donation_ID__c`
`Closed Date`

**Comment by mtuchi** [comment]
@daissatou2 here is the PR #128 with the changes for this issue 
**Direct debits**
- I have not update the `Active__c` mapping because the transformation code `If CG Status = Live, then return "True"; otherwise do not modify. ` matches what is already in the code ` Active__c: x.Status === 'Live' ? true : undefined,`
- `Closeout_Date__c` The transformation notes says the date should format `YYY-MM-DD` no timestamp, but when trying to upsert we got an error saying `"INVALID_FIELD:Failed to deserialize field at col 16. Due to, '2024-08-22' is not a valid value for the type xsd:dateTime:Closeout_Date__c --"` which means the value should be a datetime. So the current mapping for this field is datetime and not `YYY-MM-DD` ✅ 
- `CG_Pledged_Donation_ID__c` ✅ 

**Transaction DDV2**
- `CG_Pledged_Donation_ID__c` ✅ 
- `CloseDate` is already mapped in the job and there are no transformation instruction in the mapping-spec

**Comment by daissatou2** [comment]
@mtuchi please find my feedback below:

- Direct Debit: The mappings for payment frequency “Quarterly” and “SemiAnnually” were missing for the direct debits job for “CG_Pledged_Donation_ID__c”. I tried to add it with the latest commit but the log still isn’t correctly adding 3 and 6 months. See this run [log](https://openfn.org/projects/wfwi-committed-giving-staging/runs/065170a7-578d-7ea1-ad24-fc1c2a524850). You can test with this [message](https://openfn.org/projects/wfwi-committed-giving-staging/messages/0650a09b-a86f-7197-847e-e668fb2a7f3b) which has a row for each payment frequency type. 
- Transaction DD V2: The mapping for `Committed giving id` is incorrect. It looks like the id is duplicated. See line 9 of this [log](https://openfn.org/projects/wfwi-committed-giving-staging/runs/06519fb0-5ff8-7e17-9e59-f185e67f15ab).

**Comment by daissatou2** [comment]
@mtuchi On number 1: It looks like you're adding to the day instead of the month. See line 177 of this [log](https://openfn.org/projects/wfwi-committed-giving-staging/runs/0651b375-7fc9-7437-9d40-497cde747ff8) for example. Since the `Last Claim Date` is "01/09/2023 00:00:00" and the `Payment Frequency` is "SemiAnnually", the date in the `CG_Pledged_Donation_ID__c` should be "2024-03-01" not "2023-07-09".

**Comment by mtuchi** [comment]
@daissatou2 i have made some improvements [880c0b2](https://github.com/OpenFn/women-for-women/commit/880c0b263aa7ceac9590b8a445763439688a4bd3), Please test again on platform
