### ISSUE TITLE
Update Get CSVs jobs to send an email alert if no file is found

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/women-for-women#126]
## Background, context, and business value

Right now we have 2 very similar GET CSV jobs live on prod: 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js

Currently, if there is no file detected, the job simply logs "No file found". 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js#L29-L30

## The specific request, in as few words as possible

Update both of these jobs so that if a file is not found, the existing `fetchJSON` jobs should still succeed → BUT **we should _also_ send an email alert to notify WFW that this file was not detected on the SFTP server and might be missing. To do this, we will need to create a new MailChimp job `alertFilesNotFound.js`**  

![wfwi sftp filesNotFound alert](https://github.com/OpenFn/women-for-women/assets/16758106/34ceb472-0bc4-4f9a-b03c-f22922502e83)

### Email body format for Mailgun job:
Use [this existing Mailgun job](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/emailErrorAlert.js) as an example of how to map and write this job. Find the desired email format below. 

``` js
from: 'WfWI Notifications <notifications@womenforwomen.org>',
  'h:Reply-To': 'aleksa@openfn.org',
  sender: 'WfWI Notifications',
  to: 'aissatou@openfn.org, mtuchi@openfn.org',
  cc: 'aleksa@openfn.org',
  subject: 'Committed Giving Data Sync: No file found',
  html: `Dear admins, <br/><br/>
   Committed Giving file exports may have NOT been uploaded to the SFTP server for date {cursorDate}: `${state.filesNotFound}` 
   
   Please review the sftp server and upload any missing CSV exports. Contact OpenFn at <a href='mailto:support@openfn.org'>support@openfn.org</a> with any questions.`,
```

Note that the email format above contains a dynamic field: `cursorDate`. This should be yesterday's date when the sync was attempted (pls format as `YYYY-MM-DD`). 

## state.json

**sftp server** (⚠️ prod server - pls be careful w/ data)
```json
{
  "configuration": { "See LP - WFWI SFTP" },
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```
**mailgun*  (⚠️ prod server - pls only send emails TO aleksa, mtuchi, aicha)
```json
{
  "configuration": ["See LP - WfWI Mailgun Prod'"],
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

## adaptor
1. sftp
2. mailgun

## expression.js
Existing `fetchJSON` jobs to run... they should trigger a new `alertFilesNotFound.js` mailgun job to run if files are not detected on the sftp server: 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js

## output.json
An email alert to be sent when a file is not found.

**Comment by mtuchi** [comment]
@daissatou2 this issue is ready for testing once your done setting up trigger on platform

**Comment by daissatou2** [comment]
@mtuchi this is timing out on platform: https://openfn.org/projects/wfwi-committed-giving-staging/runs/0651b3f4-ae79-789f-9af1-57b03a2bb159

I tested with @ latest adaptor version and with the last 3 versions.

**Comment by mtuchi** [comment]
@daissatou2 you need `sftp@v1.0.0` i have update the job to use that version, Please try again

**Comment by daissatou2** [comment]
1. "E0. Get Donor CSVs from SFTP"  job - passed
2. "E1. Get CSVs from SFTP" job - I tested at 1pm today and there was already a file in the SFTP. I will test again much earlier tomorrow to confirm that an email is sent when a file is not found.
