### ISSUE TITLE
OpenFn Job `Upsert AD User` -- New Rule to Eliminate Extra Spaces Entered

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#13]
## The specific request, in as few words as possible
The client would like to implement a new rule for the OpenFn job `Upsert AD User` that removes extra spaces that might be the result of human error when entering data into the BambooHR system. 

The new rule is if spaces between words is >1 then eliminate extra spaces so spaces=1. Please note that the new rule applies to all BambooHR fields referenced in the mappings (everything within `"fields":{...}"` in state. 

Original mapping specs: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1713086939 

## state
See LP for the Azure portal `Microsoft (Women for Women)`. 

Clean all fields within the `"fields":{...}"`:  https://github.com/OpenFn/women-for-women/blob/master/sampleData/stateEmployeeNewEmail.json

## adaptor
`language-http`

## expression
`upsertUser.js`

## output
All of these Message states should succeed: 
https://www.openfn.org/projects/2976/messages/10105546
https://www.openfn.org/projects/2976/messages/10105506
https://www.openfn.org/projects/2976/messages/10097734

**Comment by lakhassane** [comment]
@jedbgold I don't have a message with extra spaces to test with but if you confirm that this is what is wanted you can close this issue.
At the top is the original message with `"extraaaaaa spaces"`. At the bottom is the same message cleared from `"extra spaces"`

![image](https://user-images.githubusercontent.com/8411231/100442994-d0bed500-30a0-11eb-89aa-837d68ee184f.png)

**Comment by jedbgold** [comment]
Looks great @lakhassane . Just tested and works as promised. Closing issue now.
