### ISSUE TITLE
upsertCardMasterV2: RangeError [Error]: Invalid time value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#137]
## Describe the bug
Jobs are failing on prod with this error: https://www.openfn.org/projects/wfwi-committed-giving/runs/065312e7-12cf-7364-ab0a-23ccaa045407
`RangeError [Error]: Invalid time value`

## To Reproduce
1. You can re-try the job again [this Message](https://www.openfn.org/projects/wfwi-committed-giving/messages/0652ddca-1dbe-76af-aeca-fe3c2590581c). 

### expression.js
Merge off master to troubleshoot
Link to the job itself in Github:https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMasterV2.js

### state.json
Error found when syncing to prod, so you can run with this cred to replicate (see LP: `WfWI Salesforce Production (API user)`).
But please test/troubleshoot in sandbox: 
```json
{
  "configuration": ["SEE LAST PASS: 'support@openfn.org.apiuser.fullwfwi'"],
  "data": { see above message link}
}
```

## Expected behavior
This should sync to Recurring Donations and Opportunities without error.

**Comment by mtuchi** [comment]
We have resolved this on `master` yesterday by filtering out the `Occurrence: None`, `Occurrence: ""` and `LastCredited: ""`, See - a1aedfa
