### ISSUE TITLE
Update GET CSVS jobs to not trigger email alert each time they fail

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/women-for-women#138]
## Describe the bug
The two fetch jobs currently trigger an email alert every time they fail. They should only trigger an email alert in specific scenarios. 

**fetchJSON_Donors.js: this job should trigger the email alert ONLY in the following two cases.**
1. the donor file is not found in the SFTP server
2. dupe emails detected in the donor file

**fetchJSON.js: this job should trigger the email alert ONLY in the following case.**
1. any of the files are not found in the SFTP server

Any other failure reasons SHOULD NOT trigger an email alert. 
 

## To Reproduce
1. Update the adaptor version of the job to an earlier version. This will cause it to fail and no email alert should be sent. 

### expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON_Donors.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js

### state.json

**sftp server** (⚠️ prod server - pls be careful w/ data)
```json
{
  "configuration": { "See LP - WFWI SFTP" },
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

## To test/resolve
1. After the desired output is working locally (from the CLI), please  open a pull request.
2.. Please test the change on OpenFn.org by the jobs using an old adaptor version and confirming that no email alert is triggered.

**Comment by mtuchi** [comment]
@daissatou2 i am cleaning up `missingFiles` from state to make sure every that every time the job run it will check for missing files on that day, See fix here #139

**Comment by daissatou2** [comment]
Thanks, Mtuchi! I have tested and can confirm:
1. The jobs successfully fetch today's file
2. The jobs do not trigger an email alert for errors other than the ones above (except for dupes--see comment below)


@aleksa-krolls FYI Mtuchi needs more time to test that the `fetchJSON_Donors` job does post a message to the inbox if dupes are detected. He will test with the`old/wfwi Donors 20230920.csv` file (in the "old" directory) which does have duplicates.

**Comment by mtuchi** [comment]
@daissatou2 see PR #143 for the email alert workflow when duplicates are detected. here is the example message 👇🏽 
```
{
  "__query_params": {},
  "duplicates": [
    "user1@hotmail.com",
    "user2@gmail.com"
  ],
  "notificationType": "duplicate-emails"
}
```
