### ISSUE TITLE
New Employee Email Change Request  -- 1B

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#14]
## The specific request, in as few words as possible

This refers to current job in OpenFn called `Send Welcome Email`

Everything remains the same except now when the 'New Employee' email flow is triggered:

- Send the current welcome email to `Work Email` with respective HR Divisional Officer Email cced. 
- The `Supervisor email` should **NO LONGER** be cced to this email.
- See mappings here:  [please note that this refers to flow `1B` on the sheet called `Mappings (Mailgun)`](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1626891982)

Note that new logic needs to be applied when looking up the HR Divisional Officer Email's address. 

**The new logic requirements are:**

- Look up 'HR Divisional Officer Email' by referencing the 'Division' field of the employee in the BambooHR webhook. In the W4W Integration Mappings workbook, there is a sheet called 'HR Division Email Addresses'. Use the table in HR Division Email Addresses for referencing purposes. [Please see this link for the sheet](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=925593089)

**Comment by jedbgold** [comment]
@aleksa-krolls this change is now ready.

**Comment by aleksa-krolls** [comment]
@jedbgold fyi, this is referenced in issue #16 where I added some minor changes. 

Once implemented, these changes can also easily be copied over to #15 ... but looks like we're still waiting on some Mathias feedback for this one. 

Will keep you posted when ready for testing!

**Comment by aleksa-krolls** [comment]
@jedbgold This is ready, but we'll need to ask Mathias how to test so that we don't blast real users. 

Check out the changes here: https://www.openfn.org/projects/2976/jobs/3657
