### ISSUE TITLE
Terminated Employee Email Change Request 

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#15]
## The specific request, in as few words as possible

This refers to current job in OpenFn called `Send Inactive Employee Email`

Now, when the 'Inactive Employee' email flow is triggered the client would like the following:

- In the `to` field there should be the `HR Divisional Officer Email Address` 
- in the `cc` field there should be the `helpdesk-us@womenforwomen.org` email address

The Supervisor email should **NO LONGER** be cced to this email.
See mappings here:  [please note that this refers to flow 3 on the sheet called `Mappings (Mailgun)`](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1626891982)

Note that new logic needs to be applied when looking up the `HR Divisional Officer Email`'s address.

**The new logic requirements are:**

Look up 'HR Divisional Officer Email' by referencing the 'Division' field of the employee in the BambooHR webhook. In the W4W Integration Mappings workbook, there is a sheet called 'HR Division Email Addresses'. Use the table in HR Division Email Addresses for referencing purposes. [Please see this link for the sheet](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=925593089)

**Comment by jedbgold** [comment]
@aleksa-krolls this is the beginning of the changes to the `Send Inactive Employee Email`. Next week there will likely be another change request where we will be asked to change the html message slightly to account for the insertion of a link to a survey form.

**Comment by aleksa-krolls** [comment]
@jedbgold See L30 and L31 for the new `to` and `cc` addresses implemented when ready to test. 
1. Any word from Mathias on further changes? Does the message body still look good for this alert? 
2. And does anything change about _when_ this email is sent? Currently it's triggered any time an employee status is changed to "Inactive"?

**Comment by aleksa-krolls** [comment]
@jedbgold can you confirm my question #2?

**Comment by jedbgold** [comment]
@aleksa-krolls re question #2:
No changes are to be made to the trigger.
