### ISSUE TITLE
Committed Giving Integration: Migrate project from OpenFn v1 to v2

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#150]
Migrate the v1 workflows over to OpenFn v2 to get this project on the new version and ensure Salesforce Oauth can be configured for API-only users. 

See checklist: {ADD LINK}

**Comment by daissatou2** [comment]
Checklist: https://docs.google.com/spreadsheets/d/1B7G26xgNpEDXN6ZQLtRw6s-8mgLqIloUIBvQQT_NRJw/edit#gid=1228328488
