### ISSUE TITLE
Update credit workflow to accommodate V2 migration

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/women-for-women#152]
## Background, context, and business value
Migrate the credit card workflow to V2

## The specific request, in as few words as possible

**Credit workflow jobs on V1:**
1. [E1. Get CSVs from SFTP](https://v1.openfn.org/projects/wfwi-committed-giving-staging/jobs/GU4USp)
3. [upsertCardMasterV2](https://v1.openfn.org/projects/wfwi-committed-giving-staging/jobs/ak1Cwr)
4. [upsertTransactionCardsV2](https://v1.openfn.org/projects/wfwi-committed-giving-staging/jobs/rEMQqL)
5. [upsertCustomCCV2](https://v1.openfn.org/projects/wfwi-committed-giving/jobs/jv4p86)

**Workflow on V2:** 
https://app.openfn.org/projects/d84ec7c9-7b5a-4f01-a0d2-88f359deb0e2/w/4adfe1a0-d813-4eab-b269-0ccf1f68eb0f?placeholder=true

You'll notice that the downstream jobs are not message filters but now flow jobs. Check out the suggested job changes below to make this work. 

**Suggested job changes:**
1. In V1, the `E1. Get CSVs from SFTP]` job posts messages to the inbox to trigger the other three jobs. Please update this job so that the output of the jobs contains what is in the JS path conditions on V2. Also make sure this job only fetches the credit files ("wfwi Card Master", "wfwi Transactions - Cards", and "wfwi Custom CC Fields").
3. We have added three new steps: "Chunk card master data", "Chunk transactions card data" and "Chunk custom card data". These jobs should chunk each file to account for data volume limits as done in V1.

## state.json

E1. Get CSVs from SFTP
```json
{
  "configuration": { "See LP WFWI SFTP" }
}
```

Email Alert Jobs
```json
{
  "configuration": { "See LP WfWI Mailgun Prod" }
}
```

upsertDonorsV2
```json
{
  "configuration": ["SEE LAST PASS: 'Admin user - WFW Salesforce Permissions Sandbox (Q2 2024)'"],
}
```

## adaptor
SFTP
Mailgun
Salesforce 

## expression.js

https://github.com/OpenFn/women-for-women/blob/staging/jobs/committed/1.fetchJSON.js
https://github.com/OpenFn/women-for-women/blob/staging/jobs/committed/upsertCardMasterV2.js
https://github.com/OpenFn/women-for-women/blob/staging/jobs/committed/upsertTransactionCardsV2.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomCCV2.js

The links above are to the V1 files. DO NOT MAKE ANY CHANGES TO THOSE FILES.
Create a new V2 directory in the same repo to hold the new V2 files. 

## Toggl
Lightning Migration

**Comment by aleksa-krolls** [comment]
hey @mtuchi on this one - pls note that in V2, currently `concurrency` is not configurable. Therefore it's really important that all parent records are imported in Salesforce before child records are imported. For example, we must make sure all `Card Master` records are upserted _before_ we move onto upserting `Transaction` records.
<img width="273" alt="Screenshot 2024-04-29 at 2 09 52 PM" src="https://github.com/OpenFn/women-for-women/assets/16758106/10e96f49-4b74-4f2c-b42d-164dc2b6a959">

Also, we still need to chunk/batch the number of records inserted for `Card Master`, `Transactions` , etc. Even though we are using `bulk()` operations to bulk upsert in Salesforce, there is automation on the SF-side that would fail historically if we tried to import more than `50` rows at time. Therefore, I think we still need to import records in batches of `50 records` ([see here](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js#L106) for how we chunked csvs into batches of 50 rows in the v1 implementation). 

Keep me and @daissatou2 looped in if you have any questions.

**Comment by mtuchi** [comment]
@daissatou2 i am facing this error when running `upsertCardMasterV2` step
```
[R/T] ✘ Failed step upsertCardMasterV2 after 20.193s
[R/T] ✘ AdaptorError: InvalidBatch : Field name not found : Stand_With_Her_Subtype__c
```

**Comment by mtuchi** [comment]
When mapping transaction sponsor. I am facing this error `TypeError: TypeError: Cannot read properties of undefined (reading 'split')`. This is due to a missing field called `Transaction Date`. which is used to create `CG_Pledged_Donation_ID__c` values, See mapping below  
```
CG_Pledged_Donation_ID__c: `${x.CardMasterID}_${formatDateYMD(x['Transaction Date'])}_Pledged`,
```
cc @daissatou2 
The error i am getting is for this date `20240425` files

**Comment by mtuchi** [comment]
When mapping transaction sponsor. I am facing this error `TypeError: TypeError: Cannot read properties of undefined (reading 'split')`. This is due to a missing field called `Transaction Date`. which is used to create `CG_Pledged_Donation_ID__c` values, See mapping below  
```
CG_Pledged_Donation_ID__c: `${x.CardMasterID}_${formatDateYMD(x['Transaction Date'])}_Pledged`,
```
cc @daissatou2 
The error i am getting is for this date `20240425` files

**Comment by aleksa-krolls** [comment]
@mtuchi in which file do you not find `Transaction Date`? I'm seeing it in `wfwi Transactions - Cards 20240425.csv`
<img width="526" alt="Screenshot 2024-05-07 at 12 18 56 PM" src="https://github.com/OpenFn/women-for-women/assets/16758106/e7d76870-e954-47b8-b113-3f90b219f218">

Also pls send me a link to the job line that references this mapping to help troubleshoot

**Comment by mtuchi** [comment]
@daissatou2 you can test the credit workflow using a manual cursor. Use this date 
`{ "manualCursor": "20240425" }`

**Comment by aleksa-krolls** [comment]
@daissatou2 I'm noticing the [workflow](https://app.openfn.org/projects/d84ec7c9-7b5a-4f01-a0d2-88f359deb0e2/w/4adfe1a0-d813-4eab-b269-0ccf1f68eb0f?s=79fbc5b8-d4d3-474a-b1d8-85b1748b2f4a) uses 2 credentials.... 
<img width="497" alt="Screenshot 2024-05-09 at 9 38 24 AM" src="https://github.com/OpenFn/women-for-women/assets/16758106/76a6a825-f689-4100-86e6-0aa61443229d">
<img width="274" alt="Screenshot 2024-05-09 at 9 38 19 AM" src="https://github.com/OpenFn/women-for-women/assets/16758106/6f0d8aed-f251-4fe4-aedf-3c550e41b794">

Can we pls be sure to test this with the Oauth credential? See LP `API user - WFW Salesforce Sandbox Permissions (Q2 2024)`. We should set this up as Oauth user - [see docs](https://docs.openfn.org/adaptors/salesforce#oauth2). Also note that I think the `api` scope permission will _also_ need to be selected when you set this up... lmk how it goes!

If you get it working, pls update all credentials across all WFW workflows.

**Comment by daissatou2** [comment]
@aleksa-krolls all workflows now use the API-only cred. I'll provide docs/product feedback tomorrow.

**Comment by aleksa-krolls** [comment]
@daissatou2 any luck here?
