### ISSUE TITLE
Only run automation if Division in list of "Active Divisions"

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#17]
## Background, context, and business value
Women for Women would like to phase the roll out of the automation flows gradually division by division. This will allow time for HR teams to get BambooHR employee records up to date and in the the necessary shape to insure successful data flows. 

The first `Division` that will be activated is `'Headquarters'`. Once the `Headquarters` automation is turned on, Women for Women IT administrators would like to have the ability to utilize the OpenFn platform to turn on other divisions like `Iraq` or `Kosovo` as they please.
 

See #2 for additional background. 

## The specific request, in as few words as possible
Only execute the OpenFn jobs if the Employee `Division` matches a list of "Active Divisions" (this should be an array of string values that we compare Employee to --> e.g., `const activeDivisions: [ 'Headquarters', 'Afghanistan']`. 

This should allow the admin to modify the list of `activeDivisions` to turn "on" the automation for different employees. 

If Employee `Division` is in the list of `activeDivisions` --> execute OpenFn job as is.

If Employee `Division` is NOT the list of `activeDivisions` --> stop flow; log the message `'Employee not member of activated Division. No automation executed.'`

Please see this [list for all of the divisions Women for Women has in BambooHR](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=541391866)
 (but note that the Admin should be able to add/ remove Division values from the job). 

## state.json
See [this payload](https://github.com/OpenFn/women-for-women/blob/master/sampleData/bambooMsg.json) for a sample notification received from the BambooHR webhook. This payload structure is the same for new users as well as updated user records. 

See LP for `Microsoft Azure (Women for Women)`... this is my Microsoft account which has been granted access to different WfW environments. The below test one is what we want to connect with:

Test instance name is: `WfWI Test Environment`
Domain name: `http://w4wtest.onmicrosoft.com/`

## adaptor
`language-http`

## expression.js
Apply this logic to..
`upsertUser.js`
`sendWelcomeEmail.js`
`sendInactiveEmail.js`

## output.json
Examples to test...
1. If `Division` (e.g., 'Afghanistan')  is NOT list of `activeDivisions`, then do not execute actions in Azure. Log the message `'Employee not member of activated Division. No automation executed.'`
2. If `Division` (e.g., 'Headquarters')  _is_ list of `activeDivisions`, then execute the automation flow as is.

**Comment by aleksa-krolls** [comment]
@jedbgold We have client sign-off to proceed with this request as well, yes? Please finish this issue and assign back to me if so.

**Comment by aleksa-krolls** [comment]
@lakhassane A quick one to work on today! Let me and @jedbgold know when ready to test.

**Comment by aleksa-krolls** [comment]
@lakhassane We need to apply this logic to _all_ Azure operations in the job to ensure NO Azure action is taken if employee's division is not in the list of `activeDivisions`. 
Therefore wee should _not_ assign managers, groups, or admin units if the employee division is not active... but looks like we are currently? I only see this logic evaluated in one place...
https://github.com/OpenFn/women-for-women/blob/d0b0f007e18253b51604d7a38015a5fa6c35a190/jobs/upsertUser.js#L563

**Comment by lakhassane** [comment]
Yes @aleksa-krolls the job is written in such a way that `assignManagers`, `assignAu`, etc are functions used in a giant `if...else`. So if the division condition is not respected that giant `if...else` would not be executed anyway, thus no assignment is done.

![image.png](https://images.zenhubusercontent.com/5f3bd19df7cdea0cf185f72b/8b405fbb-469e-4ba1-bd2c-5afb42ee01ff)

**Comment by aleksa-krolls** [comment]
@lakhassane thanks for clarifying! We'll test and revert back

**Comment by jedbgold** [comment]
Hi @lakhassane and @aleksa-krolls testing succeeded! When I use `Headquarters` as division automation proceeds smoothly and when I put `Afghanistan` as headquarters I get a very nice console.log that tells me "Employee not member of activated Division. No automation executed." Thank you @lakhassane 💯 Here is the testing sheet: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1544406196 

![image](https://user-images.githubusercontent.com/71792525/101308255-726bc200-3817-11eb-9351-4d974ec69fb9.png)
