### ISSUE TITLE
New job request for sending seperate welcome email to Supervisor

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#19]
## Background, context, and business value

Currently when a new employee is activated in BambooHR, the employee is sent an email containing a Microsoft password with his/her supervisor cced. The client, Women for Women, no longer would like for the supervisor to have visbility of the new employee's password. Instead, the client would like for a seperate and distinct email to be sent to the supervisor when a new employee is activated. 

## The specific request, in as few words as possible

When a new employee is activated in BambooHR, send the new employee's `supervisor email` [this email message.](https://drive.google.com/file/d/1KQpdu9azOo9Tl0zTDIx8c1lWnr98P1NJ/view?usp=sharing) 

See mappings here:  https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1626891982 

## adaptor

Adaptor mailgun

**Comment by aleksa-krolls** [comment]
@jedbgold See the new job here (https://www.openfn.org/projects/2976/jobs/3842). Questions...
1. Confirming this job has the same trigger as the Welcome emails? 
2. How to fill in `to` and `cc`?  (For now to: supervisor, and cc helpdesk)
3. Preference for email `subject`? For now: `New Account for: ${state.name} (${state.division})`)

**Comment by jedbgold** [comment]
@aleksa-krolls 

1. Confirming this job has the same trigger as the Welcome emails? **Yes.** 
2. How to fill in to and cc? (For now to: supervisor, and cc helpdesk) **To: Supervisor cc: HR Division Head (this requires the mapping logic. Refer to mapping for example: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1626891982 **
3. Preference for email subject? For now: New Account for: ${state.name} (${state.division})) **This is great**

**Comment by aleksa-krolls** [comment]
@jedbgold sorry i missed 2, thank you!
