### ISSUE TITLE
Job to integrate Microsoft AzureAD to upsert `users`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#2]
## Background, context, and business value

Women for Women wants to automate employee registration processes to save time syncing data between their BambooHR system and Microsoft Azure AD. OpenFn is configuring a prototype integration to pilot this data flow by first focusing on automation for new Employee registrations & updates. In subsequent phases, we may expand this automation to handle other employee scenarios (i.e., employee termination, contractor employees, etc.). 
- As a manager, when I register a new employee in BambooHR, I want to automatically create a new user in AzureAD so that I do not need to contact the IT Help Desk for support with this setup. 
- As a manager, when I update an employee record in BambooHR, I want to automatically update that corresponding AzureAD user so that I know important information like employee assignment is in sync. 

## The specific request, in as few words as possible
Create 1 new job to upsert `users` in MS AzureAD when we receive a notification from the BambooHR webhook. 
Inputs: 
1. See the [Phase 1 data flow](https://lucid.app/users/registerOrLogin/free?showLogin=false&pseudoEditorTitle=Women+for+Women+BambooHR+-+Azure+-+Mailgun&instructionParameter=i18nKey%23%3D%3Achart-web-controllers-invitations-document%23%40%3APN%23%3D%3Aname%23%40%3APV%23%3D%3AWomen+for+Women+BambooHR+-+Azure+-+Mailgun&invitationId=3740f42b-0ba3-4c6c-9962-014968e8bd31&product=chart)
2. [See here](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1713086939) for the mapping specifications. 
3. See this [sample `createUser.js` job](https://github.com/OpenFn/women-for-women/blob/master/jobs/createUser.js) that sends a series of HTTP requests to different Azure endpoints (this job will have more back-and-forth with Azure, but this gives you a sense of what we'll want to achieve). 
4. Use the Microsoft Graph API docs: https://docs.microsoft.com/en-us/graph/use-the-api

### Trigger
If BambooHR sends OpenFn a [notification](https://github.com/OpenFn/women-for-women/blob/master/sampleData/bambooMsg.json), check...
1. If `"Status"` is included in the `"changedFields":[...]` array (consider that there may be multiple fields) &&
2. If `"Status": "Active"` &&
3. If `"Employment Status"` = any of [these values]:(https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1247678326)
```
Fellow
Furloughed
Intern
Regular Full-Time
Regular Part-Time
Temporary Staff
```
... If criteria `1`, `2`, & `3` are true, then execute the following actions. 
If false --> then stop the flow. (NOTE: that will want to add actions in a phase 2 of this.)

### Actions
This job should automate the following actions: 
**1.1. Upsert `users`** in AzureAD
This will require us to access multiple API endpoints to... 
(1) `GET /users/${userPrincipalName}`, and then (2) `POST` or `PATCH /users/` depending on if we need to create or update. 
See [Mappings sheet](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1713086939) for user fields to map. 
Note: we need to save the user `user_id` to state to use in the subsequent actions.

> API docs: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

**1.2. Assign user to `manager`**
(1) BambooHR provides `Supervisor Email` ([see L33](https://github.com/OpenFn/women-for-women/blob/master/sampleData/bambooMsg.json#L33)). We should be able to use this to look-up and match existing managers. Not sure if we need to first search other users to find this manager's id?
(2) OpenFn to send `PUT /users/{id}/manager/$ref` request to update the manager. 

> API docs: https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http

**1.3. &  1.4. Add user as member to `groups` and `administrativeUnits`**
0. These two actions will require multiple steps where we first `POST /users/{id}/checkMemberObjects` to check which `group` and `administrativeUnit` the user has been assigned...
> API docs: https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0

AND THEN...
1.3. Add user as a member to `administrativeUnits`
`POST /directory/administrativeUnits/{id}/members/$ref`
See [this mapping sheet](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=541391866) for the administrativeUnits `adminUnitId`. 

> API docs: https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http

1.4. Add user as member to `groups`
`POST /groups/{group-id}/members/$ref`
See [this mapping sheet](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1152622566) for the groups `objectId`.

> API docs: https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http

## state.json

See [this payload](https://github.com/OpenFn/women-for-women/blob/master/sampleData/bambooMsg.json) for a sample notification received from the BambooHR webhook. This payload structure is the same for new users as well as updated user records. 

See LP for `Microsoft Azure (Women for Women)`... this is my Microsoft account which has been granted access to different WfW environments. The below test one is what we want to connect with:

Test instance name is: `WfWI Test Environment`
Domain name: `http://w4wtest.onmicrosoft.com/`
![image](https://user-images.githubusercontent.com/16758106/97422737-eb255780-1916-11eb-8d21-80da2b880880.png)

See API docs on authentication: https://docs.microsoft.com/en-us/graph/auth/auth-concepts

## adaptor

Create a **new AzureAD adaptor** to handle authentication and create basic helper functions like `upsertUser(...)`, `assignManager(...)`, `checkMemberObject(...)`, `addMemberAdminUnit(...)`, and `addMemberGroup(...)`. 

See API docs: https://docs.microsoft.com/en-us/graph/use-the-api

## expression.js
Create 1 new `upsertUser.js` job 

## output.json

Every time we receive a new BambooHR notification, upsert the `user`, assign the appropriate `manager`, `administrativeUnit`, and `Group` in Azure. 
You can access the front-end of Azure via the portal link to verify your results (see state section for more info): https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview

**Can you also please add console.logs so that we can see what body OpenFn posts to Azure? This would be helpful to confirm mappings while testing. **

**Comment by lakhassane** [comment]
@aleksa-krolls as per the request here what is the priority:
1. Create the running jobs?
2. Creating the new adaptor first, then use it for the new jobs?

**Comment by aleksa-krolls** [comment]
@lakhassane We need to do both... what's the best approach here for efficiency's sake? Doing #1 first could help to validate what helper functions we need, but I could see that doing #2 first might reduce re-work. Your choice... please just advise on timelines accordingly as you dig in :)

**Comment by lakhassane** [comment]
I think #1 would be the most appropriate. It will help see repeating pattern for a better adaptor implementation. So going for that

**Comment by aleksa-krolls** [comment]
@lakhassane How we doing on this? Can you please leave me an update on here or Slack?

**Comment by taylordowns2000** [comment]
@lakhassane , we needed an update here by EOD. I'm looking into your PR on the language-package, but please tell @aleksa-krolls what's up here.

**Comment by lakhassane** [comment]
@aleksa-krolls @jedbgold this is ready for testing when you can. I will send you a `configuration state` format for use.

**Comment by aleksa-krolls** [comment]
@lakhassane I'm not able to create nor update users and hitting `404` errors repeatedly. Any guesses why this error was thrown? What state did you test with where you were successful? 
1. When I run on prod, I encounter a `404` error in [this run failure](https://www.openfn.org/projects/2976/runs/10347098). I expect a new user to be created here. 
2. When I run locally with the `sample_data/bambooMsg.json` payload, I get the same error. 
a. Here it looks like it recognizes that Matias _does_ exist --> so it tries to update with `PATCH`, but then it throws the `404` error msg: `Resource 'MAverbuj_womenforwomen.org#EXT#@w4wtest.onmicrosoft.com' does not exist or one of its queried reference-property objects are not present`. 
b. Even when I comment out L353 `userPrincipalName`, this same error is still thrown.  
```
Adaptor
╭──────────────────────────────────────────────────────────────╮
│ ◰ ◱ ◲ ◳  OpenFn/core ~ language-http#v2.4.10 (Node v12.14.1) │
╰──────────────────────────────────────────────────────────────╯
✓ POST succeeded. (The response body will be available in state.)
Authentication done...
✓ GET succeeded. (The response body will be available in state.)
Updating user information...
✓ PATCH succeeded. (The response body will be available in state.)
Finished.
(node:48154) UnhandledPromiseRejectionWarning: Error: Server responded with:  
{
  "statusCode": 404,
  "body": "{\r\n  \"error\": {\r\n    \"code\": \"Request_ResourceNotFound\",\r\n    \"message\": \"Resource 'MAverbuj_womenforwomen.org#EXT#@w4wtest.onmicrosoft.com' does not exist or one of its queried reference-property objects are not present.\",\r\n    \"innerError\": {\r\n      \"date\": \"2020-11-03T23:30:12\",\r\n      \"request-id\": \"ac7d4340-7c19-43c9-ba4a-601cac0278c8\",\r\n      \"client-request-id\": \"ac7d4340-7c19-43c9-ba4a-601cac0278c8\"\r\n    }\r\n  }\r\n}",
  "headers": {
    "cache-control": "private",
    "content-type": "application/json",
    "request-id": "ac7d4340-7c19-43c9-ba4a-601cac0278c8",
    "client-request-id": "ac7d4340-7c19-43c9-ba4a-601cac0278c8",
    "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"West Europe\",\"Slice\":\"SliceC\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"AGSFE_IN_48\"}}",
    "x-ms-resource-unit": "1",
    "strict-transport-security": "max-age=31536000",
    "date": "Tue, 03 Nov 2020 23:30:11 GMT",
    "connection": "close",
    "content-length": "425"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "graph.microsoft.com",
      "port": 443,
      "hostname": "graph.microsoft.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/v1.0/users/MAverbuj_womenforwomen.org%23EXT%23@w4wtest.onmicrosoft.com",
      "path": "/v1.0/users/MAverbuj_womenforwomen.org%23EXT%23@w4wtest.onmicrosoft.com",
      "href": "https://graph.microsoft.com/v1.0/users/MAverbuj_womenforwomen.org%23EXT%23@w4wtest.onmicrosoft.com"
    },
    "method": "GET",
    "headers": {
      "authorization": "Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6InBNQkdjNU4xOWFvd3BocjgzNEFCSzJJeEd0cnk1LUYzemg0RFdoMkdDOTAiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yNDFmYzJmNy1hYTFjLTQxYzQtODk2OS0yMThiYzEzNmE4NzQvIiwiaWF0IjoxNjA0NDQ1OTA5LCJuYmYiOjE2MDQ0NDU5MDksImV4cCI6MTYwNDQ0OTgwOSwiYWlvIjoiRTJSZ1lHQzA4ZHI5ekhtaWlwVzE4dGNOUDUzM0FnQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJXb21lbi1mb3Itd29tZW4iLCJhcHBpZCI6ImE2OTljMGI2LWU1YzItNGQxMi05MzUwLTVmNWYxMzE1NGEwNiIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzI0MWZjMmY3LWFhMWMtNDFjNC04OTY5LTIxOGJjMTM2YTg3NC8iLCJpZHR5cCI6ImFwcCIsIm9pZCI6Ijc2ZGY5ZDY5LTg2ZDUtNDY5Yy04MWQwLTYwZjRmNTQ5MjM3YSIsInJoIjoiMC5BQUFBOThJZkpCeXF4RUdKYVNHTHdUYW9kTGJBbWFiQzVSSk5rMUJmWHhNVlNnWjFBQUEuIiwicm9sZXMiOlsiVGVhbU1lbWJlci5SZWFkLkFsbCIsIlBsYWNlLlJlYWQuQWxsIiwiUG9saWN5LlJlYWQuQ29uZGl0aW9uYWxBY2Nlc3MiLCJVc2VyU2hpZnRQcmVmZXJlbmNlcy5SZWFkLkFsbCIsIkNhbGxzLkpvaW5Hcm91cENhbGwuQWxsIiwiUG9saWN5LlJlYWRXcml0ZS5QZXJtaXNzaW9uR3JhbnQiLCJBY2Nlc3NSZXZpZXcuUmVhZFdyaXRlLk1lbWJlcnNoaXAiLCJQb2xpY3kuUmVhZFdyaXRlLkNvbmRpdGlvbmFsQWNjZXNzIiwiQml0bG9ja2VyS2V5LlJlYWRCYXNpYy5BbGwiLCJQb2xpY3kuUmVhZFdyaXRlLkF1dGhlbnRpY2F0aW9uTWV0aG9kIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWRXcml0ZS5DdXN0b21lckxvY2tib3giLCJVc2VyQXV0aGVudGljYXRpb25NZXRob2QuUmVhZC5BbGwiLCJCaXRsb2NrZXJLZXkuUmVhZC5BbGwiLCJUZWFtTWVtYmVyLlJlYWRXcml0ZU5vbk93bmVyUm9sZS5BbGwiLCJPcmdDb250YWN0LlJlYWQuQWxsIiwiUG9saWN5LlJlYWQuUGVybWlzc2lvbkdyYW50IiwiVXNlci5SZWFkV3JpdGUuQWxsIiwiUG9saWN5LlJlYWRXcml0ZS5BdXRoZW50aWNhdGlvbkZsb3dzIiwiRG9tYWluLlJlYWRXcml0ZS5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuT3duZWRCeSIsIlNlY3VyaXR5QWN0aW9ucy5SZWFkV3JpdGUuQWxsIiwiU2VjdXJpdHlFdmVudHMuUmVhZC5BbGwiLCJVc2VyQXV0aGVudGljYXRpb25NZXRob2QuUmVhZFdyaXRlLkFsbCIsIkRlbGVnYXRlZFBlcm1pc3Npb25HcmFudC5SZWFkV3JpdGUuQWxsIiwiQ2FsZW5kYXJzLlJlYWQiLCJQcml2aWxlZ2VkQWNjZXNzLlJlYWQuQXp1cmVBRCIsIlJvbGVNYW5hZ2VtZW50LlJlYWQuRGlyZWN0b3J5IiwiUG9saWN5LlJlYWRXcml0ZS5BcHBsaWNhdGlvbkNvbmZpZ3VyYXRpb24iLCJQZW9wbGUuUmVhZC5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuQWxsIiwiQ2FsbHMuSW5pdGlhdGVHcm91cENhbGwuQWxsIiwiR3JvdXAuUmVhZC5BbGwiLCJBZG1pbmlzdHJhdGl2ZVVuaXQuUmVhZC5BbGwiLCJBY2Nlc3NSZXZpZXcuUmVhZFdyaXRlLkFsbCIsIkRpcmVjdG9yeS5SZWFkV3JpdGUuQWxsIiwiQ2FsbHMuSm9pbkdyb3VwQ2FsbEFzR3Vlc3QuQWxsIiwiU2l0ZXMuUmVhZC5BbGwiLCJTaXRlcy5SZWFkV3JpdGUuQWxsIiwiQ29udGFjdHMuUmVhZFdyaXRlIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWRXcml0ZS5BZG1pbkNvbnNlbnRSZXF1ZXN0IiwiR3JvdXAuQ3JlYXRlIiwiR3JvdXAuUmVhZFdyaXRlLkFsbCIsIlNpdGVzLk1hbmFnZS5BbGwiLCJTZWN1cml0eUV2ZW50cy5SZWFkV3JpdGUuQWxsIiwiTm90ZXMuUmVhZC5BbGwiLCJDYWxsUmVjb3Jkcy5SZWFkLkFsbCIsIlVzZXIuSW52aXRlLkFsbCIsIkRpcmVjdG9yeS5SZWFkLkFsbCIsIlJvbGVNYW5hZ2VtZW50LlJlYWQuQWxsIiwiQ2FsbFJlY29yZC1Qc3RuQ2FsbHMuUmVhZC5BbGwiLCJQcml2aWxlZ2VkQWNjZXNzLlJlYWQuQXp1cmVSZXNvdXJjZXMiLCJVc2VyLlJlYWQuQWxsIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWQuQWRtaW5Db25zZW50UmVxdWVzdCIsIkRvbWFpbi5SZWFkLkFsbCIsIlVzZXJOb3RpZmljYXRpb24uUmVhZFdyaXRlLkNyZWF0ZWRCeUFwcCIsIkdyb3VwTWVtYmVyLlJlYWQuQWxsIiwiVGVhbU1lbWJlci5SZWFkV3JpdGUuQWxsIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWQuQ3VzdG9tZXJMb2NrYm94IiwiVXNlclNoaWZ0UHJlZmVyZW5jZXMuUmVhZFdyaXRlLkFsbCIsIlRydXN0RnJhbWV3b3JrS2V5U2V0LlJlYWRXcml0ZS5BbGwiLCJPcmdhbml6YXRpb24uUmVhZFdyaXRlLkFsbCIsIkFwcFJvbGVBc3NpZ25tZW50LlJlYWRXcml0ZS5BbGwiLCJQcml2aWxlZ2VkQWNjZXNzLlJlYWRXcml0ZS5BenVyZUFEIiwiVXNlci5FeHBvcnQuQWxsIiwiU2VjdXJpdHlBY3Rpb25zLlJlYWQuQWxsIiwiUHJpdmlsZWdlZEFjY2Vzcy5SZWFkV3JpdGUuQXp1cmVSZXNvdXJjZXMiLCJDYWxlbmRhcnMuUmVhZFdyaXRlIiwiQWNjZXNzUmV2aWV3LlJlYWQuQWxsIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWRXcml0ZS5Qcml2aWxpZ2VkQWNjZXNzIiwiUHJpdmlsZWdlZEFjY2Vzcy5SZWFkLkF6dXJlQURHcm91cCIsIkFwcHJvdmFsUmVxdWVzdC5SZWFkV3JpdGUuRW50aXRsZW1lbnRNYW5hZ2VtZW50IiwiVXNlci5NYW5hZ2VJZGVudGl0aWVzLkFsbCIsIk9yZ2FuaXphdGlvbi5SZWFkLkFsbCIsIlJvbGVNYW5hZ2VtZW50LlJlYWRXcml0ZS5EaXJlY3RvcnkiLCJHcm91cE1lbWJlci5SZWFkV3JpdGUuQWxsIiwiQ29udGFjdHMuUmVhZCIsIkFkbWluaXN0cmF0aXZlVW5pdC5SZWFkV3JpdGUuQWxsIiwiQXVkaXRMb2cuUmVhZC5BbGwiLCJQb2xpY3kuUmVhZC5BbGwiLCJBcHByb3ZhbFJlcXVlc3QuUmVhZC5Qcml2aWxpZ2VkQWNjZXNzIiwiTWVtYmVyLlJlYWQuSGlkZGVuIiwiQXBwbGljYXRpb24uUmVhZC5BbGwiLCJTaXRlcy5GdWxsQ29udHJvbC5BbGwiLCJQb2xpY3kuUmVhZFdyaXRlLkF1dGhvcml6YXRpb24iLCJDYWxscy5Jbml0aWF0ZS5BbGwiLCJOb3Rlcy5SZWFkV3JpdGUuQWxsIiwiQXBwcm92YWxSZXF1ZXN0LlJlYWQuRW50aXRsZW1lbnRNYW5hZ2VtZW50IiwiVHJ1c3RGcmFtZXdvcmtLZXlTZXQuUmVhZC5BbGwiLCJQb2xpY3kuUmVhZFdyaXRlLkZlYXR1cmVSb2xsb3V0IiwiUG9saWN5LlJlYWRXcml0ZS5UcnVzdEZyYW1ld29yayIsIlByaXZpbGVnZWRBY2Nlc3MuUmVhZFdyaXRlLkF6dXJlQURHcm91cCJdLCJzdWIiOiI3NmRmOWQ2OS04NmQ1LTQ2OWMtODFkMC02MGY0ZjU0OTIzN2EiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiIyNDFmYzJmNy1hYTFjLTQxYzQtODk2OS0yMThiYzEzNmE4NzQiLCJ1dGkiOiJINllDUkFlemlVS3R2LVhjTDRxcUFBIiwidmVyIjoiMS4wIiwieG1zX3RjZHQiOjE2MDMyMzg5MTV9.oSpmPWeZBPh2lkOw9K4r7Z7efd8JG9zuGXHnhUIMYSgfhhrfu3xxxasUKgqeERJro_nlXE2cGQcy2fBzL6Wuzw2P_TwtwIANBQrrtXIQfs3PniKVhMZLhJHrJk8QEYlsodytINysXZyphTl-vutx7nppFZY9TgJyOLWc-KI7Q1gE0HLnBYNZKppSZZJGGJwg1zNXVa8aR8h6_Y_gEzzU_6YnnDKaLgGaFShRDOjW6sSw7jA6dCA_vf3ZARxyz_YEcv2WFK9aPGrq_pTd1Meisnf4kvrq8HFvqU03BTCth2PnNTF8gEioFAG_M3W_SjzrmV7_a8Dnr1wUB89vqoXAow"
    }
  }
}
    at assembleError (/users/aleksakrolls/openfn-devtools/language-http/lib/Utils.js:34:10)
    at Request._callback (/users/aleksakrolls/openfn-devtools/language-http/lib/Client.js:60:40)
    at Request.self.callback (/users/aleksakrolls/openfn-devtools/language-http/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/users/aleksakrolls/openfn-devtools/language-http/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/users/aleksakrolls/openfn-devtools/language-http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
(node:48154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✓ POST succeeded. (The response body will be available in state.)
Employee is already a member of this administrative unit...
✓ POST succeeded. (The response body will be available in state.)
Employee is already a member of this group...
```

**Comment by aleksa-krolls** [comment]
@lakhassane The main big feedback so far from testing and client is that we need to _**upsert**_ `aadministrativeUnit` and `group` assignment as well as the user (not only create these assignments). 

So if we are updating a `user`.... 

**1.3.** We need to first remove existing `administrativeUnit` membership _if_ this membership is an object in the `administrativeUnitsMap`. 
--> Then we can add user as a member to the new `administrativeUnit` (this will replace the old `administrativeUnit`). 

**1.4.** We need to first remove existing `group` membership _if_ this membership is an object in the `groupMap`. 
--> Then add user as member to group (this will replace the old `group`).

**Comment by lakhassane** [comment]
@aleksa-krolls @jedbgold on this. Logic has been implemented. But I am unable to test. I am having an error as: `Authorization_RequestDenied` (as well for the version in prod right now). I can't seem to have access on Azure either. Could it be related?

**Comment by lakhassane** [comment]
Oops wrong issue.
