### ISSUE TITLE
When Division Field Left Blank in BambooHR, automatically assign user to "No Divison" Admin Unit in Azure

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#29]
## Background
Sometimes Women for Women's HR team will forget to enter a new employee's division into BambooHR. To prevent this omission from causing any issues with the new employee flow sequence, the following change is recommended:

Going forward when an employee's division field is left blank in BambooHR, this employee should automatically be assigned to a division unit in azure called `No Division`. 

## The Specific Request, in as few words as possible
Wherever referenced in the job, check state if employee `fields.Division` exists. If yes, continue to map as is. 
If not...
1. set Division value to string value to `fields.Division: 'No Division'`. Example mapping: 
https://github.com/OpenFn/women-for-women/blob/master/jobs/upsertUser.js#L635
2. then for `administrativeUnitId` mappings, update the mapping table so that `'No Division': '39d714aa-9abe-417f-a07a-c4ef698d87bd'`. Please refer to row 20 in the [`Divisions for Admin Units` in the mapping spec](https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=541391866) for more details. 
https://github.com/OpenFn/women-for-women/blob/3b65e4044b5ae7a1d92f52ada80b742b5b928296/jobs/upsertUser.js#L412

## state
See LP for `Microsoft (Women for Women)` Azure test environment. 
Use this state, but remove the Division value so (1) that `"Division": "",` OR (2) remove the `Division` key entirely to test. 
https://github.com/OpenFn/women-for-women/blob/master/sampleData/stateEmployeeNewEmail.json 

## expression
https://github.com/OpenFn/women-for-women/blob/master/jobs/upsertUser.js

**Comment by aleksa-krolls** [comment]
@lakhassane quick one for you today - please let @jedbgold know when done. 

@jedbgold do you have a Message in OpenFn that we can test with where Division is blank? Otherwise we can ask for Mathias's help testing when done.
