### ISSUE TITLE
Use BambooHR's Preferred Name in Azure's displayName When Possible

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#30]
## Background, context, and business value

At Women for Women International, some employees like to be called and referenced by their BambooHR `Preferred Name` `Middle Initial` and `Last Name`, so the transformation rule attached to the creation of Azure's `displayName` should take this into account.  

## The specific request, in as few words as possible
To generate Azure's `displayName` field apply the following transformation rule:
1. If employee `Preferred Name` exists, return `displayName: Preferred Name + Middle Initial + Last Name`. 
2. If no `Preferred Name` exists, return `displayName: First Name + Middle Initial + Last Name`. 

Refer to row 20 in the worksheet `Mappings (Bamboo-Azure)` in the workbook `Women for Women Intergrations Mapping`: https://docs.google.com/spreadsheets/d/18WNLa01o5ch2xFqVu_6tlUsvHOas-zqlKgJsi9QYWmU/edit#gid=1713086939

## state
See LP for `Microsoft (Women for Women)` Azure test environment. 
Use this state to test. 
https://github.com/OpenFn/women-for-women/blob/master/sampleData/stateEmployeeNewEmail.json 

## expression
https://github.com/OpenFn/women-for-women/blob/master/jobs/upsertUser.js
For example Alexander (BambooHR/First Name) B (BambooHR/Middle Initial) Jones (BambooHR/Last Name) prefers having the `displayName` in Azure of Alex (BambooHR/Preferred Name) B (BambooHR/Middle Initial) Jones(BambooHR/Last Name).

## output
Example 1 w. Preferred Name:
BambooHR/First Name: Millicent
BambooHR/Preferred Name: Milly
BambooHR/Middle Initial: N
BambooHR/Last Name: Doe
_Transforms to_
Azure/displayName: Milly N Doe

Example 2 w. NO Preferred Name:
BambooHR/First Name: Jane
BambooHR/Preferred Name:
BambooHR/Middle Initial: B
BambooHR/Last Name: Potter
_Transforms to_
Azure/displayName: Jane B Potter

**Comment by aleksa-krolls** [comment]
@lakhassane updating this issue spec now, but putting into backlog so you can see for today's stand up :)

**Comment by aleksa-krolls** [comment]
@lakhassane specs ready, lmk when ready to test - thanks!

**Comment by aleksa-krolls** [comment]
@lakhassane `null` is showing up in the string value returned for `displayName` if no middle name is specified. 
See `displayName: 'Matías null Averbuj'` where `"Middle initial": null`. Please update to handle null values so that it outputs `Matías Averbuj`. 
https://www.openfn.org/projects/p56pxp/runs/rzdw6r8g
