### ISSUE TITLE
Allow long-running jobs for project p56pxp

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#35]
## Request
Especially during this initial rollout phase, sometimes the client is triggering a bulk sync of data so that several records are sent from BambooHR. See Message below, and please allow for long-running jobs. 
https://openfn.org/projects/p56pxp/messages/mv773mj4

FYI, I'm pretty sure Mamadou already looked into this to confirm no job running efficiencies - so I'm pretty confident this is tied to the high data volumes we sometimes see.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 can you check this out before we sync today please? The client comes online in ~2 hours, would like to send them an update.

**Comment by taylordowns2000** [comment]
Enabled for https://openfn.org/projects/p56pxp/jobs/jvebjm
