### ISSUE TITLE
Convert Mailgun jobs to SendGrid jobs on http adaptor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#36]
## Request
For Wfw, we configured 3 jobs using `language-mailgun` that send employees and WfW staff notifications during different employee registration steps. The client is having payment issues with `Mailgun` so is wondering if we can switch them over to SendGrid (where they do have an account already setup). 

The API docs make it seem very straight forward and the mappings look the same as SendGrid. They have a little bit of budget left, so I'd like to implement this change. Hoping this will be an easy switch-over... but please keep me posted on estimates as you get started & any roadblocks.  

## state.json
See LP for `Sendgrid Wfw`. If the API token in the notes doesn't work, please read the docs on how to generate a new one. 

## adaptor
`language-http`
See [SendGrid API docs](https://sendgrid.com/docs/api-reference/) for endpoint `POST /mail/send`. 

## expression.js
Use the existing 3 email jobs to fill out the `to`, `from`, `subject`, and `html` keys and create SendGrid versions.
See here for jobs: https://github.com/OpenFn/women-for-women/tree/master/jobs/production

## output.json
Please configure on prod so that I can test. Feel free to send yourself/me test messages...
https://openfn.org/projects/p56pxp/jobs

**Comment by lakhassane** [comment]
@aleksa-krolls jobs configured from `production2` folder (so I don't overwrite the mailgun jobs). 
You are free to test whenever.
https://openfn.org/projects/p56pxp/jobs/jvqnk7
https://openfn.org/projects/p56pxp/jobs/jykzmr
https://openfn.org/projects/p56pxp/jobs/jveb7r

**Comment by aleksa-krolls** [comment]
@lakhassane looking good so far, ty!!
