### ISSUE TITLE
Committed Giving - Salesforce (Duplicate check)

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#39]
## Background, context, and business value

Women for Women International (WfWI) would like to integrate data captured by Committed Giving with Salesforce. OpenFn will sync donation data from Committed Giving to Salesforce. In addition, OpenFn to perform duplicate checking before upserting data.

For example:  As a staff at WfWI, I need to determine how many records DON'T already exist in Salesforce, so that they can be moved to Salesforce.  In addition, I need to determine contact already in Salesforce and update them with the most recent details.

## The specific request, in as few words as possible
Add logic to the `upsertDonors.js` job created in issue #42 to check multiple criteria for duplicate records before upserting Contacts in Salesforce. 

See [Mapping sheet ](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710)

1. Search Salesforce for existing `Contact` where `sf.wfw_Legacy_Supporter_ID__c === csv.PersonRef`
```
SELECT Id, FirstName, LastName, MailingAddress, HomePhone, wfw_Legacy_Support_ID__c, LastModifiedDate from CONTACT WHERE wfw_Legacy_Support_ID__c = '{csv.PersonRef}'
```

2. **If there is a match on `wfw_Legacy_Support_ID__c` ...**, 
Next compare CSV `FirstName`, `Surname`, `Address1+Address2+Address3+Address4`, `TelNumber1`,`EmailAddress` with 4 SF fields: `Name`, `MailingAddress`, `HomePhone` , `Email`. 

(i) if there is a match across ALL 4 SF fields, then this is a perfect match--> upsert this matching `Contact` in Salesforce. 

(ii) if NOT a perfect match across these 4 SF fields: compare `csv.LastChangedDateTime` with `sf.LastModifiedDate`. 
If `csv.LastChangedDateTime > sf.LastModifiedDate`, upsert  1 `Contact` in Salesforce. Upsert unique ID is  `sf.wfw_Legacy_Supporter_ID__c : csvPersonRef`.
If `csv.LastChangedDateTime < sf.LastModifiedDate`, take no action in Salesforce and log message `No Salesforce updates made for Contact with Id {personRef} because Salesforce record has more recently been updated.`

3.  **If there is NO match on `wfw_Legacy_Support_ID__c` ...**,
Upsert 1 `Contact` in Salesforce, using `sf.wfw_Legacy_Supporter_ID__c` as the unique identifier/ upsert key.
We will create a new Contact for this `donor` (and Salesforce-side duplicate rules will flag if the Contact's email/name or other details match another Contact with the same Id). 
   
## state.json
Salesforce creds: See LP for WfW Salesforce Sandbox
Committed Giving  creds:  see LP for WFWI SFTP
https://www.openfn.org/projects/pdv34m/messages/me6583p3

## adaptor
'Salesforce' adaptor

## trigger
Job will be a flow job triggered by sftp fetch. 

## expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js

**Comment by lakhassane** [comment]
@hnyende is this ready for implementation? I see it assigned but still in icebox

**Comment by hnyende** [comment]
@lakhassane not yet please. We are still waiting for sample data from WfWI.

**Comment by hnyende** [comment]
@lakhassane not yet please. We are still waiting for sample data from WfWI.

**Comment by aleksa-krolls** [comment]
@lakhassane Here is another issue expanding one of the jobs you wrote to handle advanced duplicate-checking scenarios. Let @hnyende if you have any questions.

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls it's implemented.

However I remove `MailingAddress`from the comparison in point 2 because I think we are not mapping it right.
In SF, the address comes as this: 
```
 MailingAddress: {
      city: 'Address5',
      country: 'Country',
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: 'Postcode',
      state: 'Address6',
      street: null
    },
```

If you could provide me with details from the mapping sheets which csv path should go on which sf key(e.g, Address2 => city, Address4: street, ...), I can correct the mapping.

**Comment by aleksa-krolls** [comment]
@lakhassane See rows 8-15 in this [donors sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710) for the address mapping, thanks!
