### ISSUE TITLE
Committed Giving  - Safesforce  (CSV to JSON Specs)

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#41]
## Background, context, and business value

Women for Women International (WfWI) would like to integrate data captured by Committed Giving with Salesforce. OpenFn will sync donation data from Committed Giving to
Salesforce. In addition, OpenFn to perform duplicate checking before upserting data.

For example: As a staff at WfWI, I need to get data from Committed Giving and merge it with data in salesforce.

## The specific request, in as few words as possible
To extract the source data, create a Job that gets the following CSV files from Committed Giving and converts them to JSON.
 1.  Get CSV files where the file name contains the following strings. 
        `20210517 wfwi donors`
        `20210517 wfwi live sponsorships`
        `20210517 wfwi card master`
        `20210517 wfwi Direct Debits`
        `20210517 wfwi Transactions - cards`
        `20210517 wfwi transactions - DD`
        `20210517 wfwi Custom CC fields`
        `20210517 wfwi Custom DD fields`

2. Convert each CSV exports to JSON, post to OpenFn inbox (1 Message per CSV file): https://www.openfn.org/projects/pdv34m/messages
Please include `fileName: ${CSVname}` as a tag in the message body. Also include `uploadDate` if available (similar to what we did for VCS). 

If no files found, please log the message `No new CSV files found.`

Please configure this job + creds on prod: https://www.openfn.org/projects/pdv34m/messages

## state.json
Committed Giving creds: see LP for WFWI SFTP

## adaptor
SFTP adapter to getCSVs, convert CSV2JSON

## trigger
Jobs will be timed on a weekly basis

## expression.js
Get CSV exports from SFTP and convert them to JSON

## output.json
Desired output examples
See [output example here] (https://www.openfn.org/projects/pdv34m/messages/mk5anwwv) for Custom Credit Card Details

See  [output example here](https://www.openfn.org/projects/pdv34m/messages/mn5756k7) for Custom Direct Debit Details

**Comment by aleksa-krolls** [comment]
@lakhassane I'm adding this to the backlog to begin work whenever ready (but note that Primero and WCS take priority). 
Please let @hnyende know if you have any questions.

**Comment by aleksa-krolls** [comment]
@lakhassane whenever done, can you please configure this + the credential on prod to test? 

@hnyende when Mamadou is done, we can test fetching the CSV files from the sftp server via OpenFn... these will be uploaded as Messages that we can then use for the `state` of our specs to upload this data to Salesforce :)

**Comment by lakhassane** [comment]
note @aleksa-krolls still some issues on this sftp csv streaming. But will solve asap.

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls this is ready to be continued. But noted that the file names that are in the original specs are different from the one Im seeing on the sftp server right now.

Im configuring on prod

**Comment by hnyende** [comment]
@lakhassane yes, the updated files begin with `20210517` I will update

**Comment by aleksa-krolls** [comment]
@lakhassane Please see @hnyende 's comment above... and please run this on prod to confirm it works. You can add a job and credentials here: https://openfn.org/projects/pdv34m/jobs/jywrpw

We want to check out the messages to ensure it contains the tags `fileName: ${CSVname}`. These messages will be the state for issues we're submitting later today, thanks.

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls see here a message sent to inbox: 
https://openfn.org/projects/pdv34m/messages/mpq5zw4v

You can find the others as well.

**Comment by aleksa-krolls** [comment]
@lakhassane When we stream the CSV files from sftp to OpenFn JSON, please do _not_ include the file header values as data... these should only be metadata, so skip the first row please.

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende it's taken care of.
