### ISSUE TITLE
Committed Giving - Safesforce  (JSON  to Salesforce Specs)

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#42]
## Background, context, and business value
See Issue #41 

## The specific request, in as few words as possible
Create Jobs that map the JSON objects, to Salesforce and Upserts Salesforce Objects .
See [Data Flow Diagram](https://lucid.app/lucidchart/34c8100a-42d2-47ab-8a5a-6c406a744ed8/edit?beaconFlowId=53F1EDFE7A9CEC2A&page=0_0#) 
See  [Mapping specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710) 
1. For every item in the CSV `donors` data, upsert 1 `contact` Salesforce object.
- Upsert unique ID is `sf.wfw_Legacy_Supporter_ID__c: csv.PersonRef`
- See Mapping spec - [Donors sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710).

2. For every item in the CSV `live sponsorships` data, upsert 1 `contact` and 1 `Recurring Donation` Salesforce object.
- Upsert unique ID for `contact` is `sf.wfw_Legacy_Supporter_ID__c: csv.PersonRef`
- See Mapping spec -  [Sponsorships sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1601872348).

3. For every item in the CSV `card master` data, upsert 1 `Opportunity` OR 1 `Recurring Donation` Salesforce object.
- LOGIC:  If `Occurrence=='Yearly' or 'Monthly'`, 
(1) upsert 1 `npe03__Recurring_Donation__c` record. 
(2) Otherwise... upsert 1 `Opportunity` and 1 related `npe01__OppPayment__c`.  
-  Upsert External ID is custom `sf.Committed_Giving_ID__c`
- See Mapping spec - [card master](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1843100201) 

4. For every item in the CSV `Transactions - cards` data, upsert 1 Payment `npe01__OppPayment__c` Salesforce record.
-  Upsert External ID is `sf.Committed_Giving_ID__c`
- See Mapping spec - [Transaction-card](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1387755636) 

5. For every item in the CSV `Direct Debits` data, upsert 1 `Recurring Donation` Salesforce object.
- Upsert External ID is `sf.Committed_Giving_ID__c`
- See Mapping spec - [Direct Debits](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1424769387). 

6. For every item in the CSV `Transactions DD` data, upsert 1 `Opportunity` and 1 `Payment` Salesforce record.
- Upsert External ID is `sf.Committed_Giving_ID__c`
- See Mapping spec - [Transaction-DD](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=916559361). 

## state.json
Salesforce creds: See LP for WfW Salesforce Sandbox

1. donors: https://www.openfn.org/projects/pdv34m/messages/me6583p3
2. sponsorships: https://www.openfn.org/projects/pdv34m/messages/mbp3mgkk
3. card master: https://www.openfn.org/projects/pdv34m/messages/mpq5zw4v
4. Transactions - cards: https://www.openfn.org/projects/pdv34m/messages/m78nv7mp
5. Direct Debits: https://www.openfn.org/projects/pdv34m/messages/m664nb7a
6. Transactions DD: Didn't see a Message in the OpenFn Inbox... pls fetch from sftp. 
EDIT: 6. Transactions DD: https://openfn.org/projects/pdv34m/messages/m4p8jqnq

## adaptor
`Salesforce` adaptor

## trigger
Job to be triggered by Messages created via sftp fetch ... see issue #41

## expression.js
6 new jobs (1 for each CSV source)

## output
[See Data Flows](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1967377653) for a summary of the object-level mappings. 
Map JSON objects to Salesforce objects
Upsert Salesforce objects with new records

**Comment by aleksa-krolls** [comment]
@hnyende Some feedback...
1. We should have 1 job per CSV source file (unless you plan to ask Mamadou to combine multiple source files into 1 JSON object for state)... 
2. Make sure all Salesforce fields referenced have the API name --> what is this for `Recurring Donation`, `Legacy Supporter ID`? 
3. For your request #2, I think all `transactions` should upsert 1 `Opportunity` and 1 `Payment`... seems like you forgot `Payment` here, but remembered it for #5. 
4. In the spec sometimes you say `Map` and sometimes you say `Upsert`... when describing an action in Salesforce, we should be very specific about the operation to execute. As an example, I might re-organize your job request #1 to look something like this...
```
1. For every item in the CSV `donors` data, upsert 1 `contact` Salesforce object
- Upsert unique ID is `sf.Legacy_Supporter_ID__c: csv.personRef`
- See Mapping spec - [Donors](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710) sheet
2. For every item in the CSV `sponsorships` data, upsert 1 `contact` and 1 `Recurring Donation`...
```

**Comment by aleksa-krolls** [comment]
@lakhassane Once we get the CSV files loaded as Messages into the OpenFn Inbox (see issue #41 ), then @hnyende can update this issue to provide a link to the relevant state/Message for each of these jobs. You can then begin work later today or tomorrow.

**Comment by lakhassane** [comment]
@hnyende  @aleksa-krolls one of the payload (check section `state.json` for number `6 Transactions DD`) is too large and cannot be posted to the inbox. I had a `413` in prod and locally in my machine.

So I'm going with the 1st 5 payloads
cc: @taylordowns2000

**Comment by aleksa-krolls** [comment]
@lakhassane Keep me and @hnyende posted if you're still having a hard time extracting that DD file, and if you want to discuss. 

If still struggling, we think that this first file will be very big because it contains all historical data... but going forward, it should be much smaller. Therefore, we can consider manually extracting this DD file and posting to the OpenFn Inbox in chunks so that we can test with this data... but then going forward, fetch from the SFTP server (assuming the file size will be smaller).

**Comment by lakhassane** [comment]
@hnyende every job is mapped and configured also on prod.

**Comment by hnyende** [comment]
@lakhassane thank you. Let me start testing
