### ISSUE TITLE
Custom CC and Custom DD files to salesforce specs

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#43]
## Background, context, and business value
We want to map tribute information to corresponding Opportunities to record who the donation is in honor of when donors donate money as a gift or tribute to someone else. This tribute information is collected via a form, so the form questions (metadata) are captured as data in the CSV data sources. 

See issue #41  for project background. 

## The specific request, in as few words as possible

See  [Mapping Specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=916559361) 
Create a Job that maps each row in custom CC and custom DD JSON object  to Salesforce objects and Upsert Salesforce Objects .

1. Using the `custom CC fields`, upsert `Opportunity` records. Multiple rows in the CSV will map to the same Opp. 
To map the fields, find the JSON object ("item X") with the matching `FieldName: value` as defined in column A of the mapping specs --> then return that item's `dataValue('item[X].Value')`. 
- Upsert Opportunity using Unique ID is `sf.Credit_Card_ID__c:csv.CCID`. 
- See Mapping spec - [Custom CC](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=268449680) 

2. Using the `custom DD fields`, upsert `Opportunity` records. Multiple rows in the CSV will map to the same Opp. 
To map the fields, find the JSON object ("item X") with the matching `FieldName: value` as defined in column A of the mapping specs --> then return that item's `dataValue('item[X].Value')`. 
- Upsert Opportunity using Unique ID is `sf.Direct_Debit_ID__c:csv.DDID`. 
- See Mapping spec - [Custom DD](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=215488875).

## state.json

Salesforce creds: See LP for WfW Salesforce Sandbox
1. Custom CC fields: https://www.openfn.org/projects/pdv34m/messages/m3p8e6ae
2. Custom DD fields: https://www.openfn.org/projects/pdv34m/messages/m3p8kb39
2. Debit DD fields: fetch from SFTP server

## adaptor
`Salesforce` adaptor

## trigger
Flow job triggered by Message generated from sftp fetch - see issue #41 

## expression.js
2 new jobs (1 for each CSV file)

## output
For each row in  ​JSON object, map value  in the field name key to Salesforce `Opportunity`.
Upsert Salesforce `Opportunity` with new records.

**Comment by aleksa-krolls** [comment]
@lakhassane This is ready to be worked on... heads up that the source data is structured in an interesting way, so chat with @hnyende if you need clarifications/ want to walk through this.

**Comment by lakhassane** [comment]
@hnyende I finished mapping `custom CC`and `custom DD`
