### ISSUE TITLE
Do not send Welcome Email if these conditions are met

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#44]
## Background
We have an Azure `upsertUser.js` job that runs when we receive new employee data from Bamboo. We choose not to execute actions and rather log these messages if the following criteria is met. 
https://github.com/OpenFn/women-for-women/blob/9032be921a79e749188ff5687fdc03bf0f383e74/jobs/upsertUser.js#L613-L622

## Request
Please add these same 2 criteria checks & logs to the job `sendWelcomeEmail.js`... so basically don't send the email if either of these if conditions (above) is true).

## state
See LP for `Sendgrid Wfw` ... **Please be sure not to mistakenly send an email to this employee while testing**
https://www.openfn.org/projects/p56pxp/messages/mv7qe986

## expression
https://github.com/OpenFn/women-for-women/blob/master/jobs/sendWelcomeEmail.js

**Comment by lakhassane** [comment]
@aleksa-krolls this is done and ready for testing

**Comment by aleksa-krolls** [comment]
@lakhassane I directed you to the wrong jobs, my bad :(

1. Can you please make these same commits but in the "prod" jobs in the `production` folder: https://github.com/OpenFn/women-for-women/tree/master/jobs/production2

2. Also the same changes you made to the Welcome Email job --> can you please replicate in the Supervisor Email job: https://github.com/OpenFn/women-for-women/blob/master/jobs/production2/sendSupervisorEmailProd.js

**Comment by lakhassane** [comment]
@aleksa-krolls I think the logic is already implemented for `sendWelcomeEmailProd.js`
https://github.com/OpenFn/women-for-women/blob/master/jobs/production2/sendWelcomeEmailProd.js#L588-L590

I replicated for `sendSupervisorEmailProd.js`

**Comment by aleksa-krolls** [comment]
@lakhassane I don't think the logic is quite right and doesn't include both if statements in `sendWelcomeEmailProd.js`. See this run: https://www.openfn.org/projects/p56pxp/runs/rx8594g5

In state, I see that `"Work Email": null`... this triggers [this log](https://github.com/OpenFn/women-for-women/blob/master/jobs/production2/sendWelcomeEmailProd.js#L611) to be thrown. 

Rather, I want the below logic implemented to check to make sure there is a `Work Email` defined
```
if (state.activeDivisions.includes(employee.fields.Division)) {    
   if (!employee.fields['Work Email']) {      
      state.errors.push( `No Azure actions taken because 'Work Email' not provided for ${fields['First name Last name']}.`); 
```
