### ISSUE TITLE
upsertDonors.js feedback V1

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#45]
## Describe the bug
See original issue #42 for the background. See [mapping sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1668919710) - `Donors V1` for updated mappings. 

TypeError: Cannot read property 'query' of undefined.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the `TypeError` the job encounters an undefined object https://www.openfn.org/projects/pdv34m/runs/r89ba7zd

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js

## Expected behavior
For every 1 Donor in the CSV,  1 Contact will be upserted in SF, matching on Legacy Supporter Id.

## To test/resolve
Re-run this on prod: https://www.openfn.org/projects/pdv34m/runs/r89ba7zd

**Comment by lakhassane** [comment]
@hnyende solved per our last zoom session. Awaiting long-running job.
