### ISSUE TITLE
upsertSponsorhips.js feedback V1

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#46]
## Describe the bug
A clear and concise description of what the bug is.  See original issue #42 for the background. See [mapping sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1601872348) - Sponsorships V1 for mappings.

Yellow warning. Timing needs adjustment

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pdv34m/runs/rrk3d4nd

### expression.js
Link to the job itself in Github:https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertSponsorhips.js

## Expected behavior

For every 1 live sponsorship in the CSV, 1 Contact and 1 Recurring Donation will be upserted in SF, matching on Legacy Supporter Id (triggering automation that will create related Opportunity records). 

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdv34m/runs/rrk3d4nd) and confirming success.]

**Comment by hnyende** [comment]
@lakhassane experiencing an email issue https://openfn.org/projects/pdv34m/runs/r6g4nwnx for upsertSponsorhips.js here : INVALID_EMAIL_ADDRESS: Email: invalid email address: M3 4NJ.

What do we do for these incomplete emails?

**Comment by aleksa-krolls** [comment]
As discussed - let's map `null` if invalid email address for now. To discuss with WfW.
