### ISSUE TITLE
upsertCardMaster.js feedback V1

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#47]
## Describe the bug
A clear and concise description of what the bug is. See original issue #42 for the background. See [mapping sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1843100201) - card master V1 for mappings.

TypeError [Error]: Cannot read property '2' of null

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug:

https://www.openfn.org/projects/pdv34m/runs/rrk35g7g

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMaster.js

## Expected behavior
For every 1 row in the CSV, 
if Occurrence = 'Yearly' OR 'Monthly', 
1 'Recurring Donation' will be upserted in SF matching on Committed_Giving_ID__c

Otherwise if Occurrence does NOT = 'Yearly' OR 'Monthly',  1 'Opportunity' and 1 related Payment will be upserted in SF

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdv34m/runs/rrk35g7g) and confirming success.]

**Comment by hnyende** [comment]
@lakhassane, we are getting this error `INVALID_FIELD_FOR_INSERT_UPDATE: Unable to create/update fields: npe01__Opportunity__c. Please check the security settings of this field and verify that it is read/write for your profile or permission set`. see https://openfn.org/projects/pdv34m/runs/renw6z9z

@aleksa-krolls recognised it to be a Salesforce limitation on the object npe01__OppPayment__c... and suggests that we first query for existing records using Committed_Giving_ID__c… and then update() if it exists, or create() if new.

@lakhassane please update this job to reflect the above suggestion. Please also update  upsertTransactionCards.js  and upsertTransactionDD.js with the same logic.

**Comment by lakhassane** [comment]
@hnyende I made the changes for `upsertCardMaster` and the 2 `upsertTransactionXXX` jbos

**Comment by hnyende** [comment]
@Mamadou, thanks let me re-run

**Comment by hnyende** [comment]
@lakhassane we want to create a SF record for card master only if there is a LastCreditedDate. So please update logic to use  upsertif LastCreditedDate !== null or undefined.

**Comment by aleksa-krolls** [comment]
@lakhassane Flagging that I'm not sure if `upsertIf(...)` can be used if we're using `bulk(...)` function, but this if statement should be applied. 
cc @hnyende

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende there is 3 operations (upsert, update and create) on `upsertCardMaster`. Does it mean none of them is executed if there is not a `LastCredited` date or just the one that need it (the upsert)?

**Comment by lakhassane** [comment]
@hnyende I implemented that new logic

**Comment by hnyende** [comment]
@lakhassane thanks let me re-run

**Comment by Mamadou** [comment]
Sorry, can you please remove me from this thread.
Somebody put my name in comment, and now I’m receiving all the message.

MamadouSy

**Comment by aleksa-krolls** [comment]
@hnyende see comment above :D ... be sure to tag @lakhassane on Github

**Comment by taylordowns2000** [comment]
Have deleted the comment from the wrong M.a.m.a.d.o.u., in the hopes that by deleting the comment he won't get notifications each time we chat here. Apologies, M.a.m.a.d.o.u., if you're still reading this! Hope we didn't create too much nuisance :-)
