### ISSUE TITLE
upsertCustomDD.js feedback V1

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#52]
## Describe the bug
A clear and concise description of what the bug is. See original issue #42 for the background. See [mapping sheet ](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=215488875)- Custom DD V1 for mappings.

MALFORMED_ID: Honoree Contact: id value of incorrect type: Ruby Anita Russell. 

 To map,  npsp__Honoree_Contact__c,  we may have to Search Contacts where Name = 'Ruby Anita Russell', and then return the id so that npsp__Honoree_Name__c: contactMatch.Id

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/pdv34m/runs/rd7engpb

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomDD.js

## Expected behavior
For every 1 custom DD field in the CSV,  1 Opportunity will be upserted in SF, matching on Direct_Debit_ID__c

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdv34m/runs/rd7engpb) and confirming success.]

**Comment by aleksa-krolls** [comment]
@lakhassane Similar feedback as issue #51... we need to handle the array of items. Please discuss with @hnyende how this should work, and see state: https://www.openfn.org/projects/pdv34m/messages/mmq5gnzg

**Comment by lakhassane** [comment]
@hnyende this is ready for testing

**Comment by aleksa-krolls** [comment]
@hnyende I see you moved this to Backlog... what changes need to be made or a link to a Slack thread if you were discussing with Mamadou? If you move things to backlog, you should always summarize what's needed next so that Mamadou can remember when starting this issue agin.

**Comment by lakhassane** [comment]
@hnyende please can you advise on the right column to check in `Contact`for name. I dont think there is a column `Name`in that object

**Comment by hnyende** [comment]
@lakhassane yes, we have `Name` in Contact object.
