### ISSUE TITLE
ReferenceError [Error]: host is not defined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#54]
## Describe the bug
See run here: https://openfn.org/projects/p56pxp/runs/rpdjddpk

Any guesses what's going on here? Something related to an adaptor release? 

Please feel free to re-run on prod. I'm pretty sure you own the SendGrid credential on prod.

**Comment by lakhassane** [comment]
@aleksa-krolls could you give me project access?

**Comment by aleksa-krolls** [comment]
@lakhassane access granted!

**Comment by lakhassane** [comment]
@aleksa-krolls a typo in one of the variable in the code. It's set now: https://openfn.org/projects/p56pxp/runs/rx8m8dwj
