### ISSUE TITLE
Email Duplicate Check on Donors CSV export

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#55]
## Background, context, and business value

We want to map tribute information to corresponding Opportunities to record who the donation is in honor of when donors donate money as a gift or tribute to someone else. This tribute information is collected via a form, so the form questions (metadata) are captured as data in the CSV data sources.

See issue #41 for project background.

## The specific request, in as few words as possible

There seems to be multiple Committed Giving contacts that are different records with different PrimKeys, but have the same email addresses. For example, search the `Donors` csv data for the email `christine@dufretay.com`
If 2 contacts have the same email, Salesforce will currently block us from inserting. 

Add this logic to issue #41 for `Donors` CSV export. 

1. Get CSV files where the file name contains a string with `20210517 wfwi donors`

2. Check `csv.EmailAddress` on the extracted `donors`  CSV file for any duplicate emails. 
If there exists a duplicate email,  rename each of the duplicate email. For example, if email was `hawa@openfn.org` and there exist multiple instances of this, rename to  `hawa@openfn.orgdup1`, `hawa@openfn.orgdup2`, etc

3. Convert the updated CSV export to JSON, post to OpenFn inbox (1 Message per CSV file): https://www.openfn.org/projects/pdv34m/messages
Please include fileName: ${CSVname} as a tag in the message body. Also include uploadDate if available.
## state.json

Committed Giving creds: see LP for WFWI SFTP

## adaptor

SFTP adapter to getCSVs, convert CSV2JSON

## expression.js
Get CSV exports from SFTP, check duplicate email before and rename them before converting to JSON

**Comment by lakhassane** [comment]
@hnyende this is done and ready for testing!

**Comment by hnyende** [comment]
@lakhassane thanks let me test please

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls find the latest run for `upsertDonors`: https://openfn.org/projects/pdv34m/runs/raa9za5r. There is a invalid email being set.
The wrong email is `"Pauline xxx@gmail.com"`
If you think, we should remove the part before the space whenever this happen, feel free to remove the comments I made in the code line `48` and line `53` to use the potential corrections I made
Then comment `47` and `52`.

**Comment by aleksa-krolls** [comment]
@lakhassane please see slack thread, and help @hnyende chunk donors until smaller payloads. The Messages as-is time out after 20 min.

**Comment by hnyende** [comment]
@lakhassane  can you help with this tyeerror on https://openfn.org/projects/pdv34m/runs/rrk7nmjb: TypeError [Error]: Cannot read property 'substring' of undefined

**Comment by hnyende** [comment]
@lakhassane after testing this, I get another TypeError [Error]: Cannot read property 'split' of undefined see https://openfn.org/projects/pdv34m/runs/r9wbjpjk

**Comment by lakhassane** [comment]
if `PrimKey (Committed_Giving_ID__c)` is `undefined`, then we should not try to upsert that item from the CSV array.  So, we make use of `upsertIf(...)` function where we check if dataValue('PrimKey') is defined
