### ISSUE TITLE
Validation Checks for upsertDonors.js

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#56]
## Background, context, and business value

See issue #41 for project background.

## The specific request, in as few words as possible

Add data validation checks before uploading Donor contacts. We're thinking this logic should live in `upsertDonors.js` so that we can compare with the source data in the Message, as needed... but what do you thinK? 

1. Check `json.EmailAddress` on the extracted `donors CSV` file for any invalid or null emails. If invalid or null, replace with `${json.PrimKey}@incomplete.com`

2. Check `json.EmailAddress` on the extracted `donors CSV` file for any duplicate emails.
If there exists a duplicate email,  (instead of renaming  each of the duplicate emails with dup1, dup 2, etc)...
(1) do not map this CSV row onwards to SF... so exclude from the Message?
(2) at the end of the OpenFn run, throw an error and log list of duplicate emails. **Can you please throw this error at the end of the run? Ideally, we can still proceed with uploading all other Contacts... but leave a list of dupe emails in the run log for the Admin to review at the end.**

3. Check `json.Mailing Zip/Postal Code` on the extracted `donors CSV` file for any records with more than 20 characters. If >20 char, again at the end of the OpenFn run, throw an error and log list of records with bad zip codes for the admin to review. 

##state.json
Committed Giving creds: see LP for `WFWI SFTP` 
SF: `WfW Salesforce Sandbox`
https://www.openfn.org/projects/pdv34m/messages/mdbgz56b

##adaptor
SFTP adapter to getCSVs, convert CSV2JSON

##expression.js
`upsertDonors.js`
1. Check for invalid or null emails, rename them before upserting in SF
2. Check for duplicate email, list duplicate emails + throw error
3. Check for Mailing Zip/Postal Code, list bad zip codes + throw error

**Comment by lakhassane** [comment]
@hnyende I implemented the 3 validation checks. Feel free to test
