### ISSUE TITLE
Updated Donors duplicate checking logic

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#57]
## Background, context, and business value
This extends issue #56 and #41. 

## The specific request, in as few words as possible
Client has requested changes to the steps for how we check for existing Contact records and handle invalid emails. For the new logic, see the second `Integration Flow` tab in this LucidChart diagram: https://lucid.app/lucidchart/invitations/accept/inv_b3be161a-a1bc-4a29-b576-c0f1cbc68eab?viewport_loc=2%2C439%2C2048%2C1020%2Cyw0MswWCJIR2

## state.json
See LP for `WfW Salesforce Sandbox (Imports)`

## expression.js
upsertDonors.js

## output.json
This should get around a lot of the validation rules and duplicate errors we were encountering to date.

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls so I implemented the new data flow as designed.

In the first part it says "to throw an error if emails is duplicated" which is different from the rest that says to throw error AT THE END. I don't if that is what is intended but I implemented it as is. So for any duplicated email, we immediately throw an error.

**Comment by aleksa-krolls** [comment]
@lakhassane Sorry for the lack of clarity... but all errors should be thrown at the end. There is a lot of data to process, so the goal should be to successfully process whichever records we can, and then at the end throw an error to log all the records that we were unable to upload for an admin to review... but some failures shouldn't block the entire payload from being uploaded. Please prioritize this today and let @hnyende know when done to test.

**Comment by aleksa-krolls** [comment]
@lakhassane @hnyende and I are finding TypeErrors when we are trying to post strings that have `'` within the string value. For example, the name `D'arcy`
```
MALFORMED_QUERY: 
FROM CONTACT WHERE FirstName = 'D'arcy' 
                                 ^
ERROR at Row:2:Column:42
unexpected token: arcy
```
See related runs: 
https://www.openfn.org/projects/pdv34m/runs/rj5jxmwj
https://www.openfn.org/projects/pdv34m/runs/ryawg3k8

Is there a way to format the strings... perhaps include a backlash in the string value (?)... so that we can successfully upload these Salesforce records and include the `'` character in the string values we upload. 

Please feel free to re-test on prod with the above linked Message.
