### ISSUE TITLE
Bulkify wfwi jobs to leverage `bulk()` function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#58]
## Background, context, and business value
To avoid OpenFn timeouts and SF API limits. 

## Request
Please bulkify any of the `commited` jobs we can. 

## expression
https://github.com/OpenFn/women-for-women/tree/master/jobs/committed

## state
See LP for `WfW Salesforce Sandbox`

**Comment by lakhassane** [comment]
- [ ] upsertDirectDebits
- [ ] upsertCardMaster
- [ ] upsertCustomDD

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls all the job in here are using bulk for now except `upsertDonors`.
You might want to test them and check some error as missing required fields or exceeded storage in SF.

**Comment by hnyende** [comment]
@lakhassane thanks a lot. Will test soon.
