### ISSUE TITLE
Minor user mapping issues

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#6]
## Issues
1. `mail: fields['Work email']` always seems to return `null` - why? [See run](https://www.openfn.org/projects/2976/runs/10354791). 
2. `hireDate: fields['Hire Date'],` --> convert `Hire Date` to ISO datetime format and I think this will work
3. `otherMails: fields['Home Email']` --> needs to return value formatted like `['email1', 'email2']` and _never_ return an empty array `[]` or this will fail, so consider source state value might be `null`. 
4. `businessPhones: fields['Work Phone']` --> needs to return value formatted like `['phone1', 'phone2']` and _never_ return an empty array `[]` or this will fail, so consider source state value might be `null`. 

## state
See LP for Azure creds and use [this message](https://www.openfn.org/projects/2976/messages/9929001)

## expression
https://github.com/OpenFn/women-for-women/blob/4f207a5cd71f49562c2c073cd0806391fbab0cc5/jobs/upsertUser.js#L357-L373

**Comment by lakhassane** [comment]
Changes done for `1` and `2`. For `3` and `4`, do you have an payload where we find multiple values for each? In all payload I have it's only one value so it's hard to know how we could process it. @aleksa-krolls

**Comment by aleksa-krolls** [comment]
@lakhassane on 3 and 4, I don't expect Bamboo to ever send us more than 1 value (so you can use what's in state currently). However, when we map it to Azure, Microsoft asks that we output the values in a "string collection" format (`[ 'value']`). Search `businessPhones` in [these API docs](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http) to see what I mean.

**Comment by lakhassane** [comment]
@jedbgold during test, can you confirm these mappings are getting done please.

**Comment by jedbgold** [comment]
@lakhassane yep. will do.

**Comment by jedbgold** [comment]
@aleksa-krolls can we discuss this when you have a moment?

**Comment by aleksa-krolls** [comment]
@jedbgold All testing issues resolve, just required minor tweaks. But can you please confirm that the mappings are working for those different messages in the `[11-5]` test suite... feel free to re-run the `1. Upsert Azure user` job as needed.

**Comment by jedbgold** [comment]
@lakhassane @aleksa-krolls everything in testing went smoothly. Closing issue now.
