### ISSUE TITLE
Transactions upload: `InvalidJob: Unable to parse Job`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#60]
## Describe the bug
For the `transaction` jobs I was able to resolve the Salesforce trigger error I listed in my spreadsheet... but now I'm running into this issue when trying to bulk upload `npe01__OppPayment__c` records to Salesforce. Can you please help to troubleshoot? Coordinate with @hnyende to re-run and test. 

## To Reproduce
https://www.openfn.org/projects/pdv34m/runs/rk534ge7

### expression.js
I imagine any changes will need to be applied to both...
upsertTransactionCards.js
upsertTransactionDD.js

### state.json
Cards: https://www.openfn.org/projects/pdv34m/messages/m66r77pa
Debit: https://www.openfn.org/projects/pdv34m/messages/mwbmpvgv

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende the error was because we were using `create`while it does not exist in SF. Should have used `insert`. Im replicating in the others jobs that have same.
Find the run saying that proly we need to insert Opportunity first: https://www.openfn.org/projects/pdv34m/runs/rpdjnj7x
