### ISSUE TITLE
Payments uploads don't appear in OpenFn run logs - are these executing?

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#61]
## Describe the bug
We get a successful run (https://www.openfn.org/projects/pdv34m/runs/ryapaxrz ) when trying to upload `Opportunity` and related `npe01__OppPayment__c` records in Salesforce... when I look at Salesforce, it looks like data for both objects was successfully uploaded (as expected). 

However, the run log doesn't show that the upsert step for `npe01__OppPayment__c` was executed... how can I be sure this part is working? Is there some way to ensure this step shows up in the run log? 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionCards.js#L45-L112

### expression.js
upsertTransactionCards.js

### state.json
See LP for `WfWI NEW Sandbox Salesforce`
Feel free to re-run this on prod or locally: https://www.openfn.org/projects/pdv34m/messages/ma96mnzz

## Expected behavior
Run log needs to show results for both `Opportunity` and `npe01__OppPayment__c` operations.

**Comment by lakhassane** [comment]
Ahh @aleksa-krolls this was an error that we flagged on a previous version of `salesforce (v2.3.4)`. But, using v2.3.5 will solve it: https://www.openfn.org/projects/pdv34m/runs/rpd9dxkz
