### ISSUE TITLE
ENTITY_IS_DELETED error on upsertTransactionsDD.js

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#66]
## Describe the bug

Upserting transactions DD is showing this error: 
“ENTITY_IS_DELETED:entity is deleted:

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug:      https://www.openfn.org/projects/pdv34m/runs/r3x34r5n.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionDD.js

**Comment by lakhassane** [comment]
Hey @hnyende I don't think this is a bug. It says the entity has been deleted. Can you check if that's the case?

**Comment by hnyende** [comment]
@lakhassane let me check
