### ISSUE TITLE
upsertCardMaster.js v2: new job version based on `credit master` change requests

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#68]
## Background, context, and business value
See Issue #41 that informed creation of upsertCreditMaster.js

## The specific request, in as few words as possible
Create new Job version that upserts  `npe03__Recurring_Donation__c`  Salesforce object based on data in `card master` CSV.
- See[ Data Flow Diagram](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=0_0#)
- See [Mapping specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=788718063)  for card master v2 tab

For `card master` state, see issue #70 for how these Messages should be generated. Example here: https://www.openfn.org/projects/pdv34m/messages/mwbwag8a

**LOGIC:**
For every csv row...
**1.**  Check if `csv.Occurrence`==`Yearly` or `Monthly` AND  `npe03__Amount__c`  is in multiples of 22...
**1A.** If TRUE, then upsert 1 `npe03__Recurring_Donation__c` and set :
          a) `Type__c`== `Sponsorship`
          b) `npe03__Recurring_Donation_Campaign__r.Source_Code__c ` == 'UKSPCC'`
          d) `of_Sisters_Requested__c` == calculated value* (see mapping specs & logic below)

`*` If `Occurrence===Yearly`, then `calculated value` is  `npe03__Amount__c` divided by  (12 * 22) 
If `Occurrence===Monthly`, then `calculated value` is  `npe03__Amount__c` divided by  (1 * 22) 
           E.g., 
             Monthly transaction of 22 --> `(22/(22*1)` → 1 sister
             Monthly transaction of 44 --> `44/(22*1)`→ 2 sisters
             Annual transaction 264 --> `(264/(22*12)` → 1 sister

**2.** If scenario `1` is FALSE, check if only `csv.Occurrence`==`Yearly` or `Monthly` is true (but Amount NOT a multiple of 22). 
**2A.** If TRUE, then upsert 1 `npe03__Recurring_Donation__c` and set :
          a) `Type__c`== `recurring Donation`
          b) `npe03__Recurring_Donation_Campaign__r.Source_Code__c ` == 'UKRG'`
          d) `of_Sisters_Requested__c` == undefined 
Otherwise...
**2B.** If FALSE, then stop automation flow... do not update the DB! 

## state.json
Salesforce creds: See LP for `WfWI OpenFn Sandbox Salesforce`
card master example: https://www.openfn.org/projects/pdv34m/messages/mpq5zw4v 

## adaptor
`Salesforce` adaptor

## trigger
Job to be triggered by Messages created via sftp fetch ... see issue #70 

## expression.js
Replace current job: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMaster.js

## output.json
See Data Flows for a summary of the object-level mappings.
Map `card master` JSON object to upsert `npe03__Recurring_Donation__c` Salesforce object.

**Comment by lakhassane** [comment]
@hnyende this is good to go based on our last call.

**Comment by hnyende** [comment]
@lakhassane thanks. Let me test please

**Comment by aleksa-krolls** [comment]
@lakhassane @hnyende I'm seeing that for the donor with `"PrimKey": "WFWI150320151302430340"` ([see message state](https://www.openfn.org/projects/pdv34m/messages/mk585994)), many of her transactions are being classified as "general donation" rather than "sponsorship"... but I can tell from the transaction amount (`264`) that this should be a sponsorship. To ensure this outputs correctly...

**Change request:** do NOT evaluate `Occurrence` when syncing card master... but rather only check for multiples of 22. See updated data flow diagram here: https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=0_0#

**Comment by lakhassane** [comment]
@aleksa-krolls I think it's because we are overwritting data for that PrimKey.
It appears 9 times in the message and for some of them Amount is not multiple of 22. then it gets turned to "Donation"

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls changes are made considering new data flow

**Comment by aleksa-krolls** [comment]
@lakhassane I'm seeing a successful run... but no logs from Salesforce which usually show me the record ids when records are successfully created. Is this a false success? 
https://www.openfn.org/projects/pdv34m/runs/rya4aw6d

**Comment by taylordowns2000** [comment]
@aleksa-krolls, looks like a valid :heavy_check_mark: , but that those arrays are empty. Could the logic in the filters on [35](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMasterV2.js#L35) and [49](https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMasterV2.js#L49) be wrong? 

@lakhassane , would you check on how the arrays are being created please?

```
Logging in as support@openfn.org.openfn.
Bulk upserting Sponsorship.
No items in npe03__Recurring_Donation__c array. Skipping bulk upsert operation.
Bulk upserting donations.
No items in npe03__Recurring_Donation__c array. Skipping bulk upsert operation.
Finished.
```

**Comment by lakhassane** [comment]
It's looking good Taylor. It was how the data was wrapped inside a new array. Fixed
