### ISSUE TITLE
upsertTransactionCards v2: new version of upsertTransactionCards.js job based on change requests

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#69]
## Background, context, and business value
Related to issue #69 ... we now have new logic based on the `Transaction Cards` csv to inform how we create/update Recurring Donations and Opportunities. 
Also see Issue #41 that informed the original creation of upsertTransactionCards.js... we will scrap this logic. 

## Request

Create a new Job that is triggered by `Transactions - cards CSV` messages (to replace the old job `upsertTransactionCards.js`, that will access Salesforce to...
1. Upsert `npe03__Recurring_Donation__c` object, AND/OR 
2. Upsert child `Opportunity`  records

- See[ Data Flow Diagram steps for 'Transactions -card CSV'](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=0_0#)
- See [Mapping specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1387755636)  for `Transaction card v2` tab

You will need to analyze the transaction records to see if you need to create a `Recurring Donation` record. 

Then, every 1 csv Transaction will map to 1 Opportunity in Salesforce. (Some of these Opportunities already exist but unfortunately without the external Id... so we have to implement logic to find the existing Opp, matching by the month & year of the `csv.Transaction Date` with `Opportunity.CloseDate`. This will help us either find & update the existing Opportunity record, or create a new one for this Transaction. 

## state.json 
For state, use a `transaction card` Messages generated from job spec'd in issue #70... now in Inbox, so feel free to use and run on production! 

Salesforce creds: See LP for WfW Salesforce OpenFn Sandbox

## adaptor

`Salesforce` adaptor

##trigger
Job to be triggered by Messages created via sftp fetch ... see issue #41

## expression.js

1 job for Transactions - cards CSV source 

## output.json

See [Data Flows](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=0_0#) for a summary of the object-level mappings.
Map ` Transactions - cards` JSON object to `npe03__Recurring_Donation__c` and `Opportunity` Salesforce objects
Upsert `npe03__Recurring_Donation__c` Salesforce object with new records
Upsert `Opportunity` Salesforce object with new records

**Comment by aleksa-krolls** [comment]
@lakhassane If you have any questions, I will be online for a little bit tomorrow morning to answer. Otherwise Hawa can support Thurs/Friday and I will be back Monday to help test. 

@hnyende Please note that I realized because Salesforce auto-creates Opportunities... we need to compare the CSV transaction dates with these Opportunity dates in order to figure out _which_ Opportunities to update & marked closed. I updated the diagram accordingly.

**Comment by aleksa-krolls** [comment]
@lakhassane please let @hnyende know when this transactions job is done... and she will test all the new credit jobs today and provide feedback. Thanks! :)

**Comment by lakhassane** [comment]
@hnyende this is ready to go

**Comment by hnyende** [comment]
@lakhassane thanks. Let me test

**Comment by aleksa-krolls** [comment]
I was able to resolve the initial errors because of mapping issues... but it now looks like the transaction run fails because of date formatting for `CloseDate`: 
```
"INVALID_FIELD:Failed to deserialize field at col 5. Due to, '24/10/2018 01:07:40' is not a valid value for the type xsd:date:CloseDate --"
```
https://www.openfn.org/projects/pdv34m/runs/raayjkb9

@lakhassane can you please help us with date formatting and let @hnyende know when she can re-run the transactions sync to test? Feel free to re-run on prod.

**Comment by lakhassane** [comment]
@hnyende date format solved in here. you might want to check some external id that are not available in SF: https://www.openfn.org/projects/pdv34m/runs/rrkmx3d3

**Comment by aleksa-krolls** [comment]
@lakhassane @hnyende I'm seeing negative amounts are being returned as positive.
Example state from [this message](https://www.openfn.org/projects/pdv34m/messages/mk585994)...
```
{
      "AddedBy": "nharris",
      "Amount": "-£264.00",
      "CampaignCode": "Sponsorship",
      "CardMasterID": 417500,
      "CardTransId": 413073,
      "ClientName": "Women for Women",
      "PrimKey": "WFWI150320151302430340",
      "PromoCode": "UKSPWEBCC",
      "SettlementDate": "3/12/18 22:05",
      "Status": "Paid",
      "Transaction Date": "3/12/18 16:35",
      "TransactionReference": "2-5-10531880"
    },
  ```
  See output in [run log L57](https://www.openfn.org/projects/pdv34m/runs/rn5yxnyw)... this should be a negative `-264.00`. 
  ```
  {
    Name: '2-5-10531880',
    Committed_Giving_ID__c: 'WFWI1503201513024303404175002-5-10531880',
    'npsp__Primary_Contact__r.Committed_Giving_ID__c': 'WFWI150320151302430340',
    Amount: '264.00',
  ```

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende this is ready to go
