### ISSUE TITLE
New `fetchJSONs` job that groups CSV rows before creating json Message chunks 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#70]
## Background
Issue #41 produced a job that GETs CSV files from sftp server and returns smaller chunks to post back to OpenFn inbox. The issue is that for some new job change requests in the backlog, we sometimes want to group and aggregate information on some of these CSV rows... so now we want to make sure that related CSV rows are always in the same Message state (and not have rows split between 2 Messages). 

## Request
Write a new job that...
1. extracts files with the following key words from the sftp server: `wfwi Transactions - cards` && ` wfwi card master`
2. Groups CSV rows by `CardMasterId`
3. and then chunks the data (never separating 2 rows that belong to the same CardMasterId) and posts back to the OpenFn Inbox to create new Messages

## expression
DUPLICATE this job (bc we still want to use this version for other CSV files) and create a new version: 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/1.fetchJSON.js

## state
`WFWI SFTP`
Here is what the Messages should look like where `fileType` and `fileName` are the new tags: 
https://www.openfn.org/projects/pdv34m/messages/m58nra3q

**Comment by lakhassane** [comment]
@aleksa-krolls could you clarify the grouping here.
A way to do this is to send chunks with the same `CardMasterId`. Result => we can have chunks with only 1 object or with 1000 objects (if they all have the same CardMasterId). 

Currently we chunk with 500 objects by message, but in the case we do what I wrote above we might end up with messages bigger than expected or messages with very few objects.

If it's fine I will go and push the implementation.

**Comment by aleksa-krolls** [comment]
@lakhassane Priority is that transactions with the same `CardMasterId` are NEVER split up. 

Ideally, if there is only 1 transaction for a `CardMasterId`, then we could include that in another Message that also contains different `CardMasterId` transactions... but if that's too complicated, then let's go with your suggested approach where there will be 1 Message for each `CardMasterId`'s transactions.

**Comment by lakhassane** [comment]
@aleksa-krolls pending long-running job here is a message sent to the inbox: https://www.openfn.org/projects/pdv34m/messages/mrb9eze5

it group all the CardMasterID in the same message, 146622 (present 12 times), 152267 (31 times).

**Comment by lakhassane** [comment]
Final execution https://www.openfn.org/projects/pdv34m/runs/rbgm6nda

**Comment by aleksa-krolls** [comment]
@lakhassane We need to do this again now when fetching the `Transactions DD` csv file... but for this one, we should group the CSV rows by `DDId` before chunking.

**Comment by lakhassane** [comment]
@aleksa-krolls if I did it right one change can do the trick.
https://github.com/OpenFn/women-for-women/blob/09cfd51e393c5729bbd03c372092c9790c39a1c2/jobs/committed/1.fetchJSONDuplicated.js#L87

Here if we change `DDRefforBank`with `DDId`it should group by that one before sending to inbox

**Comment by aleksa-krolls** [comment]
@lakhassane perfect! I forgot we had already implemented this for DD records :)
