### ISSUE TITLE
Update upsertTransactionDD.js  job to upsert  Recurring Donation  on `# of Sisters Requested`

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#71]
## Background, context, and business value

See original Issue #41 for background 

## The specific request, in as few words as possible

Update Transactions DD Job that upserts `npe03__Recurring_Donation__c` Salesforce object with `of_Sisters_Requested__c`

See [Data Flow Diagram](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=N580CfsFZbx8#?referringapp=slack)
See [Mapping specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=617692149) for Transactions DD V2 tab.

1. For transactions DD state, Group CSV rows by `DDRefforBank` before chunking into separate Messages see similar issue #70 for how these Messages should be generated. 

2. For every csv row. Check if `npe03__Amount__c` is in multiples of 22...

A.  If TRUE, then upsert 1 `npe03__Recurring_Donation__c` and set `of_Sisters_Requested__c` == `calculated value`* (see mapping specs & logic below)
calculated value is `npe03__Amount__c divided by (1 * 22)`
E.g.,
Monthly transaction of 22 --> (22/(22*1) → 1 sister
Monthly transaction of 44 --> 44/(22*1)→ 2 sisters

B. If FALSE, then stop automation flow... do not update `npe03__Recurring_Donation__c`

## state.json
Salesforce creds: See `LP` for `WfWI OpenFn Sandbox Salesforce`
TransactionsDD  example: https://openfn.org/projects/pdv34m/messages/m4p8jqnq

## adaptor

`Salesforce` adaptor

## trigger
Job to be triggered by Messages created via sftp fetch

## expression.js

update current job: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionDD.js 

## output.json

See Data Flows for a summary of the object-level mappings.
Map Transactions DD JSON object to upsert npe03__Recurring_Donation__c Salesforce object.

**Comment by lakhassane** [comment]
@hnyende this is ready to go. One thin to not is that issue #70 says to group by `CardMasterID`, but in here we use `DDRefforBank`. I take into account both in `1.fetchJSONDuplicated.js`.
So if you want to fetch `transaction dd`, you need to comment out line `87` of the job. And if it's the `CardMaster` of `transaction cards`, you need to comment out line `86`

**Comment by hnyende** [comment]
@lakhassane thank you. I will test this now.
