### ISSUE TITLE
upsertCardMasterV2.js Feedback v1

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#72]
## Describe the bug

1.  of of sisters not computed properly for Occurrence == `Monthly` . For example,  if Monthly Occurrence, and Amount is 22, it computes `of_Sisters_Requested__c` as 1.8333333333333333,, which rounds of as 2 in SF instead of 1.  If Amount is 44, it computes `of_Sisters_Requested__c` as 3.6666666666666665, which rounds off in SF as 4 instead of 2.  Refer to issue #68 for correct computation.

2. Some records not upserting in SF for Occurrence == `Monthly`.  Example CardMasterIDs that are not upserting in the run include: 725629, 725631 and 458381. See sample records with green highlight  here: https://docs.google.com/spreadsheets/d/1zzVrhFZrYVMzkM9goNTFdrd3BS_jWcQa5CXAMSXILfA/edit#gid=563718234 

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/pdv34m/runs/rbg9d7gj

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCardMasterV2.js 

## Expected behavior

1. If Occurrence == `Monthly`, and Amount is `22`, `of_Sisters_Requested__c` should be 1 not 1.83333333.  Refer to issue #68

2. If Occurrence == `Monthly`, the record should be upserted in SF and Type_c set to either `Sponsorship` or `Recurring Donation`  based on the LOGIC (see issue no. Refer to issue #68). 

## To test/resolve
https://www.openfn.org/projects/pdv34m/runs/rbg9d7gj

**Comment by lakhassane** [comment]
@hnyende could you advise why 3.6 should be turned to 2 and not 3?

**Comment by hnyende** [comment]
@lakhassane , just a few other things to ADD to the mapping: 
1. `npsp__PaymentMethod__c` -->   default to `credit card`
2. csv.AddedDateTime   -->   `npe03__Date_Established__c`.

**Comment by lakhassane** [comment]
@hnyende it's done

**Comment by hnyende** [comment]
@lakhassane thanks let me test
