### ISSUE TITLE
upsertDonors.js Feedback  - Trim Contact names before syncing

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#74]
## Describe the bug
 
Duplicate errors  are falsely lagged if contact names are not trimmed.  See example:   FirstName = 'Yasmin ' should be trimmed to  'Yasmin' before sync

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug:  https://www.openfn.org/projects/pdv34m/runs/r6gbkmga

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js. 

## Expected behavior
Duplicate errors should not be flagged if contact names contain extra spaces. 

## To test/resolve
https://www.openfn.org/projects/pdv34m/runs/r6gbkmga

**Comment by lakhassane** [comment]
@hnyende corrections made https://www.openfn.org/projects/pdv34m/runs/rg5656jy

**Comment by hnyende** [comment]
@lakhassane Thanks. All working fiine.
