### ISSUE TITLE
upsertTransactionCardsV2: Dynamically set Installment Period based on Amount

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#75]
## Background, context, and business value

See original Issue #41 for background

## The specific request, in as few words as possible
Update Transactions Cards v2 Job that `upserts npe03__Recurring_Donation__c` Salesforce object with `npe03__Installment_Period__c`

See  [Data flow diagram](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?beaconFlowId=0F4D957922660114&page=0_0#) 
See [Mapping specifications](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=1387755636) for Transactions Cards V2 tab.

In this job, whenever we upsert `npe03__Recurring_Donation__c` records, update the mappings to set  `npe03__Installment_Period__c` based on the triggering CSV transaction `Amount`. 

If (Amount is a multiple of 22 && < 264) || (Amount < 22), set `npe03__Installment_Period__c == "Monthly"`

Otherwise if (Amount is > 22 && NOT a multiple of 22), set `npe03__Installment_Period__c == "Yearly"`

## state.json

Salesforce creds: See `LP for WfWI OpenFn Sandbox Salesforce`
Transactions cards example: https://www.openfn.org/projects/pdv34m/runs/r7xj468b

## adaptor
`Salesforce` adaptor

## expression.js

update current job: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertTransactionCardsV2.js

## output.json

See Data Flows for a summary of the object-level mappings.
Map Transactions cards JSON object to upsert npe03__Recurring_Donation__c Salesforce object.

**Comment by aleksa-krolls** [comment]
@lakhassane please go ahead and work on this and let @hnyende know when ready for testing

**Comment by lakhassane** [comment]
@hnyende I mapped the new field

**Comment by hnyende** [comment]
@lakhassane thanks. Let me test.
