### ISSUE TITLE
New `V2` job versions for the 2`Custom` field jobs

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#77]
## Background, context, and business value
The Custom fields CSVs received from Committed Giving don't have all the info we need to look up existing Opportunities using external Ids. Therefore we need to search for the existing Opp to update using a different method. 

## Request
Please modify the existing "Custom" jobs to find existing Opportunities to update... we should never be creating new ones, and need to find existing records. 

See the `Custom Sync Logic` sheet in the [Data Flow Diagram](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?page=Vq05BR6rl1vW#) for the logic flow. 

## state.json
See LP for `WFWI OpenFn Sandbox`
Custom DD: https://www.openfn.org/projects/pdv34m/messages/mwbe47vw
Custom CC: https://www.openfn.org/projects/pdv34m/messages/m4pngkm3

## adaptor
Salesforce

## expression.js
New versions of the jobs...
upsertCustomDDV2.js
upsertCustomCCV2.js

## output.json
We should only ever be _updating_ existing Opportunities.

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende I have a question on this one.

The logic says `For every CG row...` to query matching but if not found to throw an error. However if we throw error the jobs stops and the rest of the rows will not be updated even they would have matched.

**Comment by lakhassane** [comment]
I implemented as it is said for the moment.

**Comment by aleksa-krolls** [comment]
@lakhassane When we 'update' Opps in these 2 Custom jobs, we need to make sure we're updating using the Salesforce `id` returned in the select query. It doesn't look like we're currently mapping the `id`. 
See run failure: https://www.openfn.org/projects/pdv34m/runs/rmkpg48g

Pls make sure you pull from Master before testing.

**Comment by lakhassane** [comment]
@aleksa-krolls I added the Id for both custom jobs.

See run for `upsertCustomCC`: https://www.openfn.org/projects/pdv34m/runs/r6gw8m9g
