### ISSUE TITLE
upsertTransactionDDV2.js: update operation should use `id` for externalIdField

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#81]
## Background
In the [Debit Sync Logic](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?page=N580CfsFZbx8#) flow we will either create or update Opps based on whether we can find an existing Opp by comparing transaction dates. 

## Request 
When we update existing Opps on L108, currently we use `Commited_Giving_ID__c` as the external Id... but we should instead use the record `id` returned by the Salesforce query executed on L32. Can you please update this to use the right `id` and then re-run this? 

Currently the run is failing & saying `MISSING ID`: https://www.openfn.org/projects/pdv34m/runs/rrkpzz84
Feel free to re-run on prod after you fix! 

## expression 
https://github.com/OpenFn/women-for-women/blob/92df7b264d9855e66a078fb9b8aeb17cb65243ea/jobs/committed/upsertTransactionDDV2.js#L104-L113

## state
WfW OpenFn sandbox
https://www.openfn.org/projects/pdv34m/messages/m4pnpwk3

**Comment by hnyende** [comment]
@lakhassane , Re-tested but type error: TypeError [Error]: Cannot read property 'Id' of null still on

**Comment by lakhassane** [comment]
@hnyende did you see the latest update on slack ? https://openfn.slack.com/archives/C017ELVRSM8/p1630329230002100?thread_ts=1630321518.001100&cid=C017ELVRSM8
