### ISSUE TITLE
Delete ALL Opportunity and npe03__Recurring_Donation__c records in SF

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#82]
## Background, context, and business value

This job will help reset the sandbox while we test. 
When we run the `upsertCardMasterv2 job`, the job upserts `Recurring Donation` records in Salesforce and,  Salesforce automatically generates a related `Opportunity` for each `Recurring Donation` record.  Once we make changes on the job, we need to remove existing records in Salesforce before upserting new records, mainly  for proper testing. Therefore, we need to create a job that can delete existing Recurring Donation and Opportunities in Salesforce. 

## The specific request, in as few words as possible

Create a job that deletes ALL `Opportunity` and `npe03__Recurring_Donation__c` records in Salesforce.

## state.json

See `LP for WFWI OpenFn Sandbox`

## adaptor

`Salesforce` adapter

## expression.js
To query all of these records, usually in Salesforce,  we can write query like… `Select id FROM Opportunity`

## output.json

We should delete ALL records in Recurring Donations and Opportunity salesforce objects.

**Comment by aleksa-krolls** [comment]
@lakhassane Can you please tag @hnyende when you've committed this new job so that she can configure a new job on OpenFn.org and link to this script? Remember to please test on the `openfn` sandbox (do NOT delete any data in the `apitraining` partial sandbox!!). Thanks :)

**Comment by lakhassane** [comment]
@hnyende the job is on github https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/deleteRecords.js

**Comment by hnyende** [comment]
@lakhassane thanks. Will configure immediately

**Comment by aleksa-krolls** [comment]
Hey @lakhassane @hnyende  this is failing on prod... are we waiting on adaptor changes to be pushed? See run: https://www.openfn.org/projects/pdv34m/runs/ryazpeyw

**Comment by hnyende** [comment]
@aleksa-krolls , I have updated to v2.6.0

**Comment by aleksa-krolls** [comment]
@lakhassane after it runs successfully on prod, pls double check it actually works by running those `SELECT` queries in SF to confirm all RD and Opp records deleted. 
See slack thread: https://openfn.slack.com/archives/G2LJCFFDW/p1630433352039300?thread_ts=1630431584.034800&cid=G2LJCFFDW

Latest run: https://www.openfn.org/projects/pdv34m/runs/rzdgpy5d

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 I still can't run this delete job... can you pls help? See run: https://www.openfn.org/projects/pdv34m/runs/rd746nyn

**Comment by lakhassane** [comment]
@aleksa-krolls successfully deleted: https://www.openfn.org/projects/pdv34m/runs/r44grenx

There was an option missing in the job as per the latest adaptor changes `{failOnError: true}`
