### ISSUE TITLE
upsertTransactionCardsV2: negative sponsorship donation amount logged as 'General Giving'

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#84]
## Issue
I think Hawa is right that there's something off with the multipleof22-checking logic and the fact that it's a negative number. See slack thread: https://openfn.slack.com/archives/C017ELVRSM8/p1630410922000600 

See [NEW__Credit RD Logic](https://lucid.app/lucidchart/5fde689a-2c21-4e07-ad7f-4808cbc134f9/edit?page=jvg9dnz.p6DI#) sheet for the modified logic flow and my notes since I made changes to your job to eliminate some transaction steps. 

Then, see L109 in Hawa's run: https://www.openfn.org/projects/pdv34m/runs/rmkp7nyz
Amount is `-264` which is a multiple of 22, so we expect `Donation_Type__c: 'Sponorship'` (NOT general giving). 

## expression
upsertTransactionCardsV2.js 

## state
See LP for `WfWI OpenFn Sandbox`
See run that you can feel free to re-run on prod: https://www.openfn.org/projects/pdv34m/runs/rmkp7nyz

**Comment by lakhassane** [comment]
@aleksa-krolls @hnyende I pushed the logic according to the latest changes
