### ISSUE TITLE
Delete old `Pledged` CG Opportunities

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#85]
## Background, context, and business value
When we upload historical RDs, SF sometimes auto-creates Opportunities. 

## The specific request, in as few words as possible
After we upload all Opps (transactions), we want to run a job to delete all of these auto-generated Opportunities that are no longer expected donation opportunities to help reset donation projections. 

## state.json

See `LP for WFWI OpenFn Sandbox`

## adaptor

`Salesforce` adaptor

## expression.js
New job that will use this query...
`SELECT Id from Opportunity WHERE Committed_Giving_ID__c <> null AND StageName = 'Pledged' AND CloseDate < TODAY()`

## output.json
Delete all CG "Pledged" Opps where `CloseDate < today()`.

**Comment by lakhassane** [comment]
@aleksa-krolls this is done. is it safe to configure on prod and run?

**Comment by aleksa-krolls** [comment]
@lakhassane Fyi, I adjusted the query slightly bc I realize what we want to delete is a little different... but working beautifully, thanks!
https://www.openfn.org/projects/pdv34m/runs/rmkpg8wd
