### ISSUE TITLE
upsertDonors: TypeError [Error]: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#86]
## Describe the bug
I've cleared the sandbox and am trying to re-sync donors... but hitting this error: 
https://www.openfn.org/projects/pdv34m/runs/ryaz45nj

### expression.js
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js

### state.json
**Please make sure you're using this sandbox:** `WfWI OpenFn Sandbox`
https://www.openfn.org/projects/pdv34m/messages/mpq8q9wk

**Comment by aleksa-krolls** [comment]
@lakhassane Also please see this other donor run where there seem to be lots of addresses with a `"Blank"` value... can you please clean these values in the `upsertDonors` job? 
See run: https://www.openfn.org/projects/pdv34m/runs/rk5pjkny
See state: https://www.openfn.org/projects/pdv34m/messages/mn58zrdb

**Comment by lakhassane** [comment]
@aleksa-krolls I pushed a fix for the original issue. 

For your last comment is the run you posted exact? It's the same as the one in the specs above? Also could you point a line with those blanks address and what do you mean by "clean"

**Comment by lakhassane** [comment]
Ok I see them at the end of the run. Could you precise what cleaning means here because this is how those address are: 
`"Address1": "Blank",`

**Comment by aleksa-krolls** [comment]
@lakhassane please map as follows, but check all Address fields (Address1, Address2). Thanks!
`Address1: "Address1"==="Blank" ? undefined : dataValue(Address1)`

**Comment by lakhassane** [comment]
@aleksa-krolls I made a function that would replace Blank with undefined but Im unable to test because I can't trigger the same conditions that will Log the duplicates.

However you can see the snippet added here: 
https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js#L18-L22
