### ISSUE TITLE
`custom` jobs: find Honoree Contact, and create if record does not exist

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#87]
## Background, context, and business value
Sometimes when people donate, they want to make a donation in honor of someone... and WfWI therefore wants to then notify that "honoree contact" by sending them emails and sometimes a paper card. To make sure they can easily communicate with these honoree contacts, they want to make sure these people are logged as individual `Contact` records in their CRM. 

## Request
To both custom jobs, we need to fill in the lookup field `Opportunity.npsp__Honoree_Contact__c`. Therefore, please add the below mapping to the job where `contactId` is the record `Id` of the matching Contact record. 
`field('npsp__Honoree_Contact__c', contactId),`

To find the matching Contact record and its `contactId`...
1. search for an existing Contact with a matching email...
`SELECT Id FROM Contact WHERE email = {csv.Notify Email Address}`
2. If none found, then search for an existing Contact with a matching name...
`SELECT Id FROM Contact WHERE Name = {csv.Notify Name}`

If no existing `contactId` found, then insert a new Contact to generate a new record and return its `Id` to later map to `npsp__Honoree_Contact__c`.
```
upsert('Contact', 'Email', {
  FirstName: dataValue(Notify Name).split(" ")[0], //find firstname from CSV name
  LastName: dataValue(Notify Name).split(" ")[1], //find lasttname from CSV name
  Email: dataValue(Notify Email Address)
});
```
Return `npsp__Honoree_Contact__c: contactId`

## state.json
See LP for `WFWI OpenFn Sandbox`
Custom DD: https://www.openfn.org/projects/pdv34m/messages/mwbe47vw
Custom CC: https://www.openfn.org/projects/pdv34m/messages/m4pngkm3

## adaptor
Salesforce

## expression.js
Please make this change in both jobs
upsertCustomDDV2.js
upsertCustomCCV2.js

## output.json
We either need to find the existing `Contact.Id`, or create a `Contact` and then use its record `Id` to then complete the mapping: 
`field('npsp__Honoree_Contact__c', contactId),`

**Comment by aleksa-krolls** [comment]
@lakhassane how's it going here? Any questions? Keep me posted if helpful to talk through today :)

**Comment by lakhassane** [comment]
@aleksa-krolls I was searching for a way to do it without looping many times in the json to avoid timeout.

I mapped the new version for `upsertCustommCCV2` please have a look whenever you can.
There is 2 questions in there for you Line `77` and Line `87`

**Comment by lakhassane** [comment]
I added same for `upsertCustomDDV2` with questions in the job

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks for the notes! I addressed your questions re: `FirstName` and `Email` by updating the mappings directly. 

Re: your question `if no notify name and email should we update with empty contactId?`...
Can you please implement a change on both jobs to NOT map the field `npsp__Honoree_Contact__c` if `state.data['Notify Email Address']=== undefined  OR null`.

**Comment by lakhassane** [comment]
@aleksa-krolls I implemented that change
