### ISSUE TITLE
New `CardMaster` job: Set old RDs as "inactive" if recent RD is cancelled

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#88]
## Background, context, and business value
If a recurring donations are cancelled, we should ensure that all existing Recurring Donations created in Salesforce before that cancellation date are also canceled. 

## The specific request, in as few words as possible
For every CSV card master item `x` where `x.RecurringCancelDate` is defined...
1. Find existing active RDs for this Donor in Salesforce...
```
SELECT Id, npe03__Date_Established__c  FROM npe03__Recurring_Donation__c WHERE Active__c = TRUE AND npe03__Contact__r.Committed_Giving_Id__c = {x.PrimKey} AND  npe03__Date_Established__c < {x.RecurringCancelDate}
```
2. If there are results returned by this query, it's because there are some RDs that were created before one RD was cancelled (`RD.npe03__Date_Established__c`< `x.RecurringCancelDate`). In such cases, we update those RDs as follows to deactivate these old RDs...
```
For every RD found in SF...
update('npe03__Recurring_Donation__c', {
    Id: queryResults.Id, 
    Active__c: false,
    Closeout_Date__c: x.RecurringCancelDate, 
    Closeout_Reason__c: x.RecurringCancelReason,
    npe03__Next_Payment_Date__c: null
})
```
3. If no results returned by the query in step 1, then stop flow and log message: `No earlier Recurring Donations found to deactivate. Skipping cancellation/closeout step.` 

## state.json
Salesforce creds: See LP for WfWI OpenFn Sandbox Salesforce
card master example: https://www.openfn.org/projects/pdv34m/messages/mpq5zw4v

## adaptor
salesforce

## expression.js
New flow job `deactivateRecurringDonations.js`

## output.json
In SF... all of Ute's other RDs are marked as "Active". However, because one of the RDs has `Closeout Date: 22/10/2019`, all of her other RDs should be marked as "inactive" because they were created (see `Date Established`) before this cancellation date.
<img width="962" alt="Screen Shot 2021-09-09 at 3 59 10 PM" src="https://user-images.githubusercontent.com/16758106/132690309-7c79b36d-2b6c-4e88-a8a6-111abecf2886.png">

**Comment by lakhassane** [comment]
@aleksa-krolls I made a draft of this logic.

How I understand your point 3 here is we log the message but we don't necessarily stop the whole flow and should keep going for the other rows.

**Comment by aleksa-krolls** [comment]
@lakhassane if this is done, can you pls (1) link the job here (https://www.openfn.org/projects/pdv34m/jobs/jyd9zp), and (2) set the correct adaptor version.

**Comment by lakhassane** [comment]
@aleksa-krolls it's linked

**Comment by aleksa-krolls** [comment]
@lakhassane do you remember why the 'bulkified' lines are commented out on this job? Are you waiting to test something?

**Comment by aleksa-krolls** [comment]
@lakhassane Please test _locally_ with the `openfn` sandbox. (Note: the prod jobs are currently linked to another sandbox... so pls do NOT test on prod yet for this.)

Fyi, there are several RD records in there, so you can test individually... or in a bulkified way. You can use any of these messages to test: https://www.openfn.org/projects/pdv34m/messages?dateRange=custom&endDate=2021-09-23T17%3A54%3A32.804Z&jobStates=&page=1&perPage=10&searchString=&startDate=2021-08-24T17%3A54%3A28.379Z&triggerId=t9v7w7

**Comment by lakhassane** [comment]
@aleksa-krolls doing it successfully: 
1st run : fetch RDs and deactivate them : https://www.openfn.org/projects/pdv34m/runs/06155b3f-b6d0-7665-9a57-765c088b8c03

2nd run: fetch same RDs but log that there are already deactivated: https://www.openfn.org/projects/pdv34m/runs/06155b41-856a-7184-9c1f-3b3dcbbe54f4

**Comment by aleksa-krolls** [comment]
@lakhassane In this job we throw an error `No recurring donations to deactivate` if no RDs to update. Keep this log, but please don't throw an error. It's okay if there are no RDs to deactivate... this should still succeed. 

See failure example & feel free to re-run on prod: 
https://www.openfn.org/projects/pdv34m/runs/06156c36-759d-7c61-8a56-e10a26c538dc

**Comment by lakhassane** [comment]
Alright made the change. https://www.openfn.org/projects/pdv34m/runs/06156d4b-ed35-7aa5-af4e-2574343d6149

No throwing error anymore
