### ISSUE TITLE
JSON_PARSER_ERROR: Cannot deserialize instance of date from VALUE_STRING value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#89]
## Describe the bug
See run with failure: 
`JSON_PARSER_ERROR: Cannot deserialize instance of date from VALUE_STRING value 11/2/2021 17:43:40 or request may be missing a required field at [line:1, column:460]`

1. Is there a `formatDate(...)` function we can borrow from the other jobs and apply to all the `Opt_In_Date `mappings (e.g., `Mail_Opt_in_Date__c? 
2. Also I noticed that mappings are repeated a lot in this job... any way we can build 1 mapping object of the mappings that are common across the different scenarios/operations? 

## To Reproduce
Feel free to re-run on prod: https://www.openfn.org/projects/pdv34m/runs/rzd8xjdn

### expression.js
upsertDonors.js

### state.json
See `WfW OpenFn Sandbox Salesforce`
https://www.openfn.org/projects/pdv34m/messages/mpqegq9n

## Expected behavior
`Opt_In_Date` fields and any dates should be in Salesforce-friendly ISO format.

**Comment by aleksa-krolls** [comment]
@lakhassane pls re-run on prod until we get a green check, and let me know if I can help!

**Comment by lakhassane** [comment]
@aleksa-krolls I rework this one and:
1. correct the date issue
2. refactor the mapping.

So I used a generic `baseMapping` that centralizes all the fields to upsert https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonorsV2.js#L17-L80

The job looks lighter and at least avoid those duplications.
I pushed the changes to `upsertDonorsV2.js` that I linked to the job on prod so you can test and not lose the previous version of `upsertDonors.js`.

Here is the latest run: https://www.openfn.org/projects/pdv34m/runs/rbgnpg8j
