### ISSUE TITLE
console.log revisions 

### ISSUE THREAD

**Issue by jedbgold** [OpenFn/women-for-women#9]
## Background, context, and business value

Women for Women would like an easier way to be able to filter jobs. To accomodate this, we would like to make some changes to `console.log` and `Error` messages.

## The specific request, in as few words as possible

Revise `console.log` messages to reflect the messages written on this [google doc](https://docs.google.com/document/d/1AJ0sAoZPdjs3hC8F1w7NlBgDe1WGNvmYsEO1lndtWlE/edit#heading=h.sx38r1qhfrq8)

**Comment by taylordowns2000** [comment]
@jedbgold , this looks straightforward and it seems you've already written the code in that google doc. Are you implementing this, or would you like @lakhassane to help out? (If so, please put this in the backlog and prioritise accordingly.)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane ready to implement. Goal is to give the admin user better feedback on what is going on.

**Comment by aleksa-krolls** [comment]
@lakhassane Looking good, thanks. And @jedbgold the docs look good for now. Let's sit tight and wait for Matias's feedback.
