### ISSUE TITLE
upsertDonorsV2: `formatDate()` function returning dates in 1900s (instead of 2000s)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#91]
## Request
Sometimes in the CSV state, dates will be formatted as: `Gift Aid date: '1/12/2017 09:05:00'`
This is currently outputting in SF as: `wfw_Date_of_Declaration_Confirmation__c: '01/12/1917'` (instead of `2017`)

## expression
https://github.com/OpenFn/women-for-women/blob/4b37133fd6278a350cee77b4c0c6d0676172bf3e/jobs/committed/upsertDonorsV2.js#L76

## state
See `WFWI OpenFn Sandox`
See L6701 where ` "Gift Aid date": "1/12/2017 09:05:00",`
https://www.openfn.org/projects/pdv34m/messages/m4pzr68a

**Comment by lakhassane** [comment]
@aleksa-krolls do you have a example run so I can see the issue?

Using the formatDate on the example you gave me this is what is returned
<img width="302" alt="Screen Shot 2021-09-23 at 13 26 21" src="https://user-images.githubusercontent.com/8411231/134515335-ea0ecb5d-dce2-4df4-9c70-428261da8bc5.png">
