### ISSUE TITLE
New job to fetch only Donors csv & clean duplicate rows before chunking

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#92]
## Background
In test with the latest `donors` csv extract, we're finding that there are dupe records with the _same_ `EmailAddress` - see this sheet for examples: https://docs.google.com/spreadsheets/d/1hZkRHm5xJZReSlZ5KKErDwJw0LVPMgDKOkVRa058aWs/edit#gid=465632478

These rows need to be addressed by the admin immediately, and should not be synced with Salesforce. 

## Request
_Before_ we chunk the donor records, we want to:
1. remove any duplicate rows from the JSON & log an error (change request), and then... 
2. chunk the remaining donors & post to the OpenFn Inbox (current behavior)

If rows with dupe `EmailAddress`, remove all rows from the json state. And then throw the error at the end of the run...
```
console.log('Potential duplicate rows detected in Committed Giving. See rows:', JSON.stringify(dupeRows, null, 2));
```

## expression
I've created a new job that is a dupe of the other fetch jobs... but this one will get `wfwi donors` only. 
https://github.com/OpenFn/women-for-women/blob/ca2509e13807bf3d328ecc6cc363031eabaa91dd/jobs/committed/1.fetchJSON_Donors.js#L1-L106

## state
See LP `WFWI SFTP`

**Comment by lakhassane** [comment]
@aleksa-krolls changes done: https://www.openfn.org/projects/pdv34m/jobs/jywada

But we are timing out: https://www.openfn.org/projects/pdv34m/runs/rk58mbey
@taylordowns2000 can you make this job above a long running please?

**Comment by aleksa-krolls** [comment]
@lakhassane see my Slack comment... I'm worried all the data isn't being posted back to OpenFn: https://openfn.slack.com/archives/G2LJCFFDW/p1632420235020700?thread_ts=1632410419.015400&cid=G2LJCFFDW

**Comment by aleksa-krolls** [comment]
@lakhassane I'm seeing the message now... were you able to fix something? 
https://www.openfn.org/projects/pdv34m/messages/mj49j9pe

**Comment by lakhassane** [comment]
@aleksa-krolls yes. It was a filtering issue where empty `EmailAddress` were removed

**Comment by aleksa-krolls** [comment]
@lakhassane This fetch job is correctly flagging duplicate rows - see run: https://www.openfn.org/projects/pdv34m/runs/06155ff8-c34c-766e-9971-7952950b8921
`Error: Potential duplicate rows detected in Committed Giving. See rows:`

However, we are not removing these dupe rows from the Messages we post to the Inbox. See Message L242 that contains a duplicate donor: https://www.openfn.org/projects/pdv34m/messages/06156005-9d6e-7c81-91c6-6fc35591c5ed

We need to...
1. Scan CSV for duplicate emails
2. Remove all rows from state where there is a potential duplicate (so that they're not mistakenly synced to SF)
3. Post cleaned state as chunked Messages to OpenFn Inbox
4. Throw error at end & log a list of the dupe rows removed in step 2

(Currently we're not doing step 3, so dupe data is still being synced to SF.)

**Comment by aleksa-krolls** [comment]
@lakhassane I think it worked now! But I'll test some more and let you know if anything else pops up. Closing for now.
