### ISSUE TITLE
upsertDonorsV2: TypeError [Error]: Cannot read property '2' of null

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#93]
## Describe the bug
See run failure: https://www.openfn.org/projects/pdv34m/runs/r3xkepn4

## To Reproduce
Feel free to re-run on prod or locally

### expression.js
upsertDonorsV2.js

### state.json
See `WfWI OpenFn Sandbox`
https://www.openfn.org/projects/pdv34m/messages/mdb4d4gb

**Comment by aleksa-krolls** [comment]
@lakhassane Looks like this was caused by a weirdly-generated Message... the CSV columns do not match the correct data values. I'm going to move out of backlog until we run your new `fetch donors` job... we can then check if this is still an issue.

**Comment by aleksa-krolls** [comment]
Found a more recent error... updated the issue.

**Comment by lakhassane** [comment]
@aleksa-krolls issue corrected with `Gift Aid Date: "True"`
See run here throwing duplicates error: https://www.openfn.org/projects/pdv34m/runs/rd7987wp

**Comment by aleksa-krolls** [comment]
@lakhassane Something is wrong here... when I check the source csv file, there is a date in this `Gift Aid Date` column
<img width="626" alt="Screen Shot 2021-09-24 at 9 05 56 PM" src="https://user-images.githubusercontent.com/16758106/134720936-b7016449-5453-4954-ab4c-21dfa3bf25c5.png">

But when I look at the Message state (see L891 in [this message](https://www.openfn.org/projects/pdv34m/messages/mdb4d4gb), it looks like the Column headers & data values are misaligned. Is it possible the source data somehow got corrupted when fetching it via the job `1.fetchJSON_Donors.js` (see issue #92 ).

**Comment by lakhassane** [comment]
@aleksa-krolls I think this might be a typo in the csv itself. In the generated json all the rows are correct except one where date and status are swapped.
Could you verify in the csv if you have quick access to it for  `"PersonRef": "454413164"` if `Gift Aid Date` and `Gift Aid Status` are in the correct order?

**Comment by aleksa-krolls** [comment]
@lakhassane See screenshot from my last comment... the csv looks good. I therefore wonder if something went wrong when we fetch the donors csv from the sftp server? (See LP for `WFWI SFTP` if you want to inspect the source file yourself)

**Comment by lakhassane** [comment]
@aleksa-krolls job re-run https://www.openfn.org/projects/pdv34m/runs/06151fa1-3758-7053-b174-dfbab2ac0173
