### ISSUE TITLE
upsertDonorsV2.js: TypeError [Error]: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#95]
## Describe the bug
See run failure: https://www.openfn.org/projects/pdv34m/runs/rzd874re

## To Reproduce
Feel free to re-run on prod or locally

### expression.js
upsertDonorsV2.js

### state.json
See `WfWI OpenFn Sandbox`
https://www.openfn.org/projects/pdv34m/messages/me6n4nqb

**Comment by lakhassane** [comment]
@aleksa-krolls issue corrected here as well: https://www.openfn.org/projects/pdv34m/runs/rn53759x

**Comment by lakhassane** [comment]
correction made here: https://www.openfn.org/projects/pdv34m/runs/renze349
