### ISSUE TITLE
upsertDonorsV2: Add step to check `Committed_Giving_ID__c` before proceeding with duplicate-checking flow

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#96]
## Background, context, and business value
In issue #57 we implemented a flow for checking for existing dupe Contacts in Salesforce before merging records. 
We realized that this flow is important for historical records, but once we go live... for faster processing, we should check if the SF record has already been assigned a Committed Giving ID before going through all the dupe-checking steps. 

## The specific request, in as few words as possible
Before executing any of the steps involving queries to Salesforce... please add a step to check if a Contact with a matching `Committed_Giving_ID__c` exists already in Salesforce... if yes, then we can sync with this record and don't need to complete all of the dupe-checking steps for this donor. 
```
Select Id, FirstName, Email, LastModifiedDate from Contact where Committed_Giving_ID__c = `${csv.PrimKey}`
```

If result > 1, then check if the `sf.LastModifiedDate` < `cg.LastChangedDateTime`. Only if CG data is more recent, proceed with updating the matching Contact. 
If CG data _not_ more recent, the run succeeds... but log the message: `Skipping update. Salesforce Contact is more recent for ${PrimKey} - ${FirstName} ${LastName}`

If a Contact does NOT exist in SF with matching `Committed_Giving_ID__c`... then proceed with the dupe-checking flow as is. See pink-outlined steps added in this updated data flow: https://lucid.app/lucidchart/4d0b44a8-3299-431f-84b5-4b00bc713cd7/edit?shared=true&page=yw0MswWCJIR2#

## state.json
See LP for `WfWI OpenFn Sandbox`
Sample state: https://www.openfn.org/projects/pdv34m/messages/m585k5vm

## expression.js
upsertDonorsV2.js

**Comment by lakhassane** [comment]
@aleksa-krolls made the change here : https://www.openfn.org/projects/pdv34m/runs/06152ef5-9d99-742a-b899-68ab56bc9dad

Do you have an idea what we should do about `LastName`?  It's always undefined in state.

**Comment by aleksa-krolls** [comment]
@lakhassane Thank you! Can you use `Surname` instead of `LastName`? (surname = csv, lastname = sf name)
