### ISSUE TITLE
Update Transactions to link to match RD (only if parent RD found)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#98]
## Background
Sometimes Opps existing in SF need to be linked to Recurring Donations we create via the integration. We know this by matching the Card Master ID. 

## Request
Pls create new bulk job that relates stray `Opportunity` records with parent `npe03__Recurring_Donation__c` that we insert via this integration. 

1. Query all `Opportunity` with `CG_Credit_Card_Master_ID__c` and RD not defined. 
```
Select Id, CG_Credit_Card_Master_ID__c from Opportunity WHERE CG_Credit_Card_Master_ID__c != null and npe03__Recurring_Donation__c = null
```
2. Return a list of `cardMasterIds` from these Opps found. 
3. Then find `npe03__Recurring_Donation__c` records that have a matching `CG_Credit_Card_ID__c`. (So find `RD.CG_Credit_Card_ID__c` that = `Opp.CG_Credit_Card_Master_ID__c`)
```
Select Id, CG_Credit_Card_ID__c  from npe03__Recurring_Donation__c where CG_Credit_Card_ID__c in cardMasterIds
```
4. Return a list of `matchingRDs`. 

5. Then match the RDs with the Opportunities queried in step 1.
(So find `matchingRD.CG_Credit_Card_ID__c` that = `Opp.CG_Credit_Card_Master_ID__c`)

6. If a matching RD is found, update only these Opportunities so that...
`Opportunity.npe03__Recurring_Donation__c = matchingRD.Id`

Result should link `Opportunities` with parent `npe03__Recurring_Donation__c` records if `RD.CG_Credit_Card_ID__c` = `Opp.CG_Credit_Card_Master_ID__c`. 

## expression
New bulk job 
`matchOppsWithRDs.js`

## state
Timer job
See LP for `WfWI OpenFn Sandbox`

## Testing
Please link to here & test on prod: https://www.openfn.org/projects/pdv34m/jobs/jvbjxx
(I want to ensure no long-running job needed.)

**Comment by aleksa-krolls** [comment]
@lakhassane whenever this is ready, please see `Testing` notes and keep me posted if you think we need a long-running job... hopefully not :D

**Comment by lakhassane** [comment]
@aleksa-krolls any LP cred to test here?

**Comment by lakhassane** [comment]
@aleksa-krolls run here but no match found: https://www.openfn.org/projects/pdv34m/runs/061573bc-d7dc-7082-9636-a089126f6d29

Don't think this needs to be a long-running job

**Comment by aleksa-krolls** [comment]
@lakhassane This second query is not working because there are definitely matches. 
Per the run log, it looks like this returns 0 returns. 
```
Executing query: SELECT Id, CG_Credit_Card_ID__c  from npe03__Recurring_Donation__c WHERE CG_Credit_Card_ID__c in 
  ('265978','326041','166346','394758','401521','417087','417502','482338','584592','602633','633294','668790','672347','694857','720206','722337','725629')
  
{ totalSize: 0, done: true, records: [] }
```

However, if I query for just 1 of these Ids, then Salesforce does return one result. 
```
Select Id, CG_Credit_Card_ID__c from npe03__Recurring_Donation__c WHERE CG_Credit_Card_ID__c = '725629'
```
![Screen Shot 2021-10-04 at 1.05.10 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/127907ad-048b-4208-8c98-281a33b842a6)

Can you please troubleshoot? There should definitely be matching RDs for these.

**Comment by aleksa-krolls** [comment]
@lakhassane So I'm testing in the "partial" training sandbox where I know there are matches. 
It seemed to find matching RDs, but check out this run failure:
`ERROR_HTTP_414: Bad Message 414</h1><pre>reason: URI Too Long`
 https://www.openfn.org/projects/pdv34m/runs/0615ad78-acc6-7a7c-aa64-70743685bcdf

See the `Request Size Limits` section of the API docs: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm

Is there perhaps a way to chunk queries or something to avoid this limit?

**Comment by aleksa-krolls** [comment]
@lakhassane also one more request to add onto step 3 in my issue above. When querying RDs, can you also check the RD `Type__c`? 
```
Select Id, Type__c, CG_Credit_Card_ID__c  from npe03__Recurring_Donation__c where CG_Credit_Card_ID__c in cardMasterIds
```
Then, if updating `Opportunity` to link the matching parent `npe03__Recurring_Donation__c`... ALSO update Donation Type: 
`Opportunity.Donation_Type__c: RdType === 'Recurring Donation' ? 'Recurring Donation' : undefined
```

**Comment by lakhassane** [comment]
@aleksa-krolls I implemented the logic we discussed but hitting an error saying object Opportunities does not exist:  https://www.openfn.org/projects/pdv34m/runs/0615b383-f822-7fbb-aadb-f0715919b12d

**Comment by aleksa-krolls** [comment]
@lakhassane Looks like your operation was `bulk(
  'Opportunities',` instead of `Opportunity`. 

All good now, thanks!

**Comment by aleksa-krolls** [comment]
@lakhassane This isn't quite working... if there are 4 Opportunities with 1 matching parent RD, only one of the 4 Opportunities are updated. 
For example, see this job duplicate I made where I added a filter to only search for Opps with the `CG_Credit_Card_Master_ID__c = '604564'` to test a smaller batch: 
https://www.openfn.org/projects/pdv34m/jobs/jvr5k3

Then see run where only 1 of the 4 Opportunity records are linked to the parent RD: 
https://www.openfn.org/projects/pdv34m/runs/0615b701-1987-7da5-8f00-6e19cefd8d21

I expect all Opportunities to be updated in order to look-up to this matching parent RD.

**Comment by lakhassane** [comment]
@aleksa-krolls I updated accordingly.
