### ISSUE TITLE
upsertCustomCCV2.js: Throw error of job at the end if no matching Opp

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#99]
## Request
If matching Opportunity not found, then please throw the error again... this way the entire message is evaluated and 1 error does not block syncing of all data. 
See example run that throws error only after part of the payload has been mapped: https://www.openfn.org/projects/pdv34m/runs/06156303-4e21-7bdf-ae75-f7f85727aa07

## expression
https://github.com/OpenFn/women-for-women/blob/9bb697cdb3f6640e257b0c8e27235ab855d73ffc/jobs/committed/upsertCustomCCV2.js#L42-L43

## state
`WfWI Partial Sandbox`
Feel free to process on prod: 
https://www.openfn.org/projects/pdv34m/messages/06141ee6-b000-7a5d-84b8-834bd134f49f

**Comment by lakhassane** [comment]
@aleksa-krolls I have a question here.

What do you mean `throw the error again?`

**Comment by lakhassane** [comment]
@aleksa-krolls change done
